<?php
require_once __DIR__.'/../../lib/auth.php';requireAuth();require_once __DIR__.'/../../lib/branding.php';
$activePage=$activePage??'scan';$searchPlaceholder=$searchPlaceholder??'Search candidate, skill or role';$headerUser=currentUser();$brand=organizationBrand();$pageTitle=brandedPageTitle($pageTitle??null,$brand);$favicon=$brand['logo_path']?:'data:image/svg+xml,'.rawurlencode('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="12" fill="#6f45ff"/><text x="32" y="42" text-anchor="middle" font-size="34" fill="white">N</text></svg>');$pageStyles='<link rel="icon" href="'.htmlspecialchars($favicon,ENT_QUOTES).'">'.($pageStyles??'');
$nav=[
  ['analytics','analytics.php','fa-chart-line','Analytics','Analytics — Hiring Metrics'],
  ['dashboard','dashboard.php','fa-chart-pie','Dashboard','Dashboard — Overview & Activity'],
  ['candidates','candidates.php','fa-users','Candidates','Candidates — Applicant Database'],
  ['calendar','interview_calendar.php','fa-calendar-days','Interviews','Interviews — Candidate Slots'],
  ['outreach','outreach.php','fa-paper-plane','Hiring Outreach','Hiring Outreach — Create Campaign'],
  ['outreach_history','outreach_history.php','fa-clock-rotate-left','Outreach History','Outreach History — Campaign Reports'],
  ['email_history','email_batch_history.php','fa-envelope-open-text','Email History & Resets','Email History — Dispatches & Batch Resets'],
  ['integrations','integrations.php','fa-plug','Integrations','Integrations — Email & SMTP'],
  ['scan','index.php','fa-file-arrow-up','Resume Upload','Resume Upload — Parse & Ingest Resume'],
  ['settings','settings.php','fa-gear','Settings','Settings — Account & Branding']
];
$wishlistCount=0;$profileCount=0;try{$s=db()->prepare("SELECT COUNT(*) items,COUNT(DISTINCT wi.profile_id) profiles FROM wishlist_items wi JOIN wishlist_profiles wp ON wp.id=wi.profile_id WHERE wp.user_id=? AND wi.disposition='wishlist'");$s->execute([$headerUser['id']]);$c=$s->fetch();$wishlistCount=(int)($c['items']??0);$profileCount=(int)($c['profiles']??0);}catch(Throwable $e){}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=htmlspecialchars($pageTitle)?></title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"><link rel="stylesheet" href="assets/app.css"><link rel="stylesheet" href="assets/header-actions.css"><?=$pageStyles??''?>
<style>
.brand-icon img{width:30px;height:30px;object-fit:contain;border-radius:7px}
.side-btn{position:relative}
.side-btn[data-tooltip]:hover::before{content:attr(data-tooltip);position:absolute;left:calc(100% + 12px);top:50%;transform:translateY(-50%);background:#1e1b2e;color:#fff;font-size:11px;font-weight:600;white-space:nowrap;padding:6px 12px;border-radius:8px;box-shadow:0 6px 18px rgba(0,0,0,0.18);pointer-events:none;z-index:120;letter-spacing:-0.01em}
.side-btn[data-tooltip]:hover::after{content:"";position:absolute;left:calc(100% + 4px);top:50%;transform:translateY(-50%);border-width:5px 6px 5px 0;border-style:solid;border-color:transparent #1e1b2e transparent transparent;pointer-events:none;z-index:120}
</style>
</head><body><div class="app"><aside class="sidebar"><a class="brand-icon" href="dashboard.php" aria-label="<?=htmlspecialchars($brand['name'])?>"><?php if($brand['logo_path']):?><img src="<?=htmlspecialchars($brand['logo_path'])?>" alt=""><?php else:?><i class="fa-solid fa-cube"></i><?php endif?></a><nav class="side-nav"><?php foreach($nav as [$key,$href,$icon,$label,$tooltip]):?><a class="side-btn <?=$activePage===$key?'active':''?>" href="<?=$href?>" title="<?=$label?>" data-tooltip="<?=htmlspecialchars($tooltip)?>"><i class="fa-solid <?=$icon?>"></i></a><?php endforeach?></nav><div class="side-bottom"><a class="side-btn" href="logout.php" title="Logout" data-tooltip="Logout — Exit Session"><i class="fa-solid fa-right-from-bracket"></i></a></div></aside><div class="main"><header class="topbar"><a class="logo" href="dashboard.php"><?=htmlspecialchars($brand['name'])?></a><form class="global-search" action="candidates.php" method="get" role="search"><button type="submit" aria-label="Search candidates"><i class="fa-solid fa-magnifying-glass"></i></button><input id="globalSearch" name="q" value="<?=htmlspecialchars(trim((string)($_GET['q']??'')))?>" placeholder="Name or skills, comma separated" autocomplete="off"></form><nav class="mobile-nav"><?php foreach($nav as [$key,$href,$icon,$label,$tooltip]):?><a class="<?=$activePage===$key?'active':''?>" href="<?=$href?>"><?=$label?></a><?php endforeach?></nav><div class="top-actions"><a class="top-wishlist" href="wishlist.php" title="<?=$profileCount?> wishlist profiles"><i class="fa-regular fa-heart"></i><span><?=$wishlistCount?></span></a><a class="account-chip" href="settings.php"><span class="avatar"><?=htmlspecialchars(strtoupper(substr($headerUser['name']??'RI',0,2)))?></span><span class="account-copy"><strong><?=htmlspecialchars($headerUser['name']??'Profile')?></strong><small>Profile & settings</small></span></a></div></header><main class="content">
