<?php
require_once __DIR__.'/lib/auth.php';requireAuth();require_once __DIR__.'/lib/workspace.php';
$items=loadCandidateRecords();$pdo=db();$bySource=[];$gapCount=0;$missing=['email'=>0,'country'=>0,'phone'=>0,'experience'=>0];$emails=[];
foreach($items as $c){$source=$c['source']??'Unknown';$bySource[$source]['total']=($bySource[$source]['total']??0)+1;if(in_array($c['stage']??'',['Interview','Offer'],true))$bySource[$source]['converted']=($bySource[$source]['converted']??0)+1;if(!empty($c['experience']['gaps']))$gapCount++;if(empty($c['email']))$missing['email']++;if(empty($c['country_code'])&&empty($c['country_name']))$missing['country']++;if(empty($c['phone']))$missing['phone']++;if(empty($c['experience']['total_months']))$missing['experience']++;if(!empty($c['email']))$emails[mb_strtolower($c['email'])]=($emails[mb_strtolower($c['email'])]??0)+1;}
$duplicates=array_sum(array_map(fn($n)=>max(0,$n-1),$emails));$roleKey=fn($v)=>preg_replace('/\s+/',' ',preg_replace('/^sr\.?\s+/','senior ',mb_strtolower(trim((string)$v))));$profiles=$pdo->query('SELECT id,name,required_skills_json FROM wishlist_profiles ORDER BY name')->fetchAll();$coverage=[];$jobScores=[];
foreach($profiles as $profile){$required=json_decode($profile['required_skills_json']??'[]',true)?:[];if(!$required)continue;$eligible=array_values(array_filter($items,fn($c)=>$roleKey($c['role']??'')===$roleKey($profile['name'])));if(!$eligible)continue;foreach($eligible as $candidate){$match=profileSkillMatch($candidate,$required);$jobScores[$profile['name']][]=$match['score'];foreach($required as $skill){$key=normaliseSkill($skill);$coverage[$key]['label']=$skill;$coverage[$key]['required_in'] = ($coverage[$key]['required_in']??0)+1;if(in_array($skill,$match['matched'],true))$coverage[$key]['matched']=($coverage[$key]['matched']??0)+1;}}}
foreach($coverage as &$row){$row['matched']=$row['matched']??0;$row['percent']=$row['required_in']?(int)round($row['matched']/$row['required_in']*100):0;}unset($row);uasort($coverage,fn($a,$b)=>$a['percent']<=>$b['percent']);$mail=$pdo->query('SELECT status,COUNT(*) total FROM email_recipients GROUP BY status')->fetchAll();
$activePage='dashboard';$pageTitle='Analytics · ResumeIQ';$pageStyles='<style>.analytics-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin-top:10px}.analytics-panel{padding:17px}.analytics-panel h2{font-size:13px;margin:0 0 13px}.data-row{display:grid;grid-template-columns:150px 1fr 90px;gap:8px;align-items:center;padding:8px 0;border-bottom:1px solid var(--line);font-size:9px}.data-row:hover{background:#faf9ff}.track{height:7px;background:#eeeef5;border-radius:4px;overflow:hidden}.track i{height:100%;display:block;background:var(--primary)}.quality-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.quality-card{padding:11px;border:1px solid var(--line);border-radius:8px}.quality-card strong{display:block;font-size:18px}.quality-card span{font-size:8px;color:var(--muted)}.unavailable{padding:13px;background:#fafafe;border:1px dashed var(--line);color:var(--muted);font-size:9px}@media(max-width:760px){.analytics-grid{grid-template-columns:1fr}}</style>';require __DIR__.'/views/partials/header.php';
?>
<section class="page-head"><div><div class="kicker"><i class="fa-solid fa-chart-line"></i> Hiring intelligence</div><h1>Analytics</h1><p>Only configured job skills and actual resume data are measured.</p></div><a class="btn" href="dashboard.php">Dashboard</a></section>
<section class="analytics-grid"><article class="panel analytics-panel"><h2>Skill coverage / shortage</h2><?php foreach($coverage as $row):?><a class="data-row" href="candidates.php?skill=<?=urlencode($row['label'])?>"><span><?=htmlspecialchars($row['label'])?></span><div class="track"><i style="width:<?=$row['percent']?>%"></i></div><b><?=$row['percent']?>% · <?=$row['matched']?>/<?=$row['required_in']?></b></a><?php endforeach?><?php if(!$coverage):?><div class="unavailable">Configure required skills inside a job profile. CSS, JavaScript, React, Blockchain and other real skills will then appear here.</div><?php endif?></article>
<article class="panel analytics-panel"><h2>Job profile match</h2><?php foreach($jobScores as $job=>$scores):$avg=(int)round(array_sum($scores)/count($scores));?><a class="data-row" href="candidates.php?job=<?=urlencode($job)?>"><span><?=htmlspecialchars(trim($job))?></span><div class="track"><i style="width:<?=$avg?>%"></i></div><b><?=$avg?>%</b></a><?php endforeach?><?php if(!$jobScores):?><div class="unavailable">Add required skills to calculate job-specific match.</div><?php endif?></article>
<article class="panel analytics-panel"><h2>Website vs upload vs Drive conversion</h2><?php foreach($bySource as $source=>$x):$rate=$x['total']?round(($x['converted']??0)/$x['total']*100):0;?><div class="data-row"><span><?=htmlspecialchars($source)?></span><div class="track"><i style="width:<?=$rate?>%"></i></div><b><?=$rate?>%</b></div><?php endforeach?></article>
<article class="panel analytics-panel"><h2>Employment, duplicates and data quality</h2><div class="quality-grid"><div class="quality-card"><strong><?=$gapCount?></strong><span>Employment gaps</span></div><div class="quality-card"><strong><?=$duplicates?></strong><span>Duplicate emails</span></div><?php foreach($missing as $key=>$count):?><div class="quality-card"><strong><?=$count?></strong><span>Missing <?=htmlspecialchars($key)?></span></div><?php endforeach?></div></article>
<article class="panel analytics-panel"><h2>Email delivery / failure report</h2><?php foreach($mail as $row):?><div class="data-row"><span><?=htmlspecialchars(ucfirst($row['status']))?></span><div></div><b><?=$row['total']?></b></div><?php endforeach?><?php if(!$mail):?><div class="unavailable">No email events yet.</div><?php endif?></article><article class="panel analytics-panel"><h2>Timeline and interviews</h2><div class="unavailable">Pipeline timing and reschedule metrics will appear after event history is collected.</div></article></section>
<?php require __DIR__.'/views/partials/footer.php';?>
