<?php
require_once __DIR__.'/lib/auth.php'; requireAuth();
require_once __DIR__.'/lib/workspace.php';
$items=loadCandidateRecords();
$skills=[];
foreach($items as $candidate) foreach(($candidate['skills']??[]) as $skill) if(trim($skill)!=='') $skills[mb_strtolower(trim($skill))]=trim($skill);
natcasesort($skills);
$activePage='candidates'; $pageTitle='Candidates · ResumeIQ';
$pageStyles='<style>.candidate-layout{display:grid;grid-template-columns:230px 1fr;gap:10px;margin-top:12px}.filters,.candidate-list{padding:15px}.field{margin-top:12px}.field label{display:block;font-size:9px;color:var(--muted);margin-bottom:5px}.candidate-row{display:grid;grid-template-columns:42px 1fr auto;gap:11px;align-items:center;padding:12px;border-bottom:1px solid var(--line)}.candidate-row:hover{background:#faf9ff}.avatar-sm{width:40px;height:40px;border-radius:10px;background:var(--primary-soft);color:var(--primary);display:grid;place-items:center;font-weight:700}.candidate-row strong{font-size:11px}.candidate-row p{font-size:9px;color:var(--muted);margin:4px 0}.row-meta{text-align:right}.row-meta b{display:block;font-size:13px}.row-meta span{font-size:8px;color:var(--muted)}@media(max-width:760px){.candidate-layout{grid-template-columns:1fr}.candidate-row{grid-template-columns:40px 1fr}.row-meta{grid-column:2;text-align:left}}</style>';
require __DIR__.'/views/partials/header.php';
?>
<section class="page-head"><div><div class="kicker"><i class="fa-solid fa-users"></i> Candidate intelligence</div><h1>All candidates</h1><p><?=count($items)?> candidates with an available resume. Open a candidate for score, skills and experience evidence.</p></div><a class="btn btn-primary" href="index.php"><i class="fa-solid fa-cloud-arrow-up"></i>Upload resume</a></section>
<section class="candidate-layout"><aside class="panel filters"><b>Filters</b>
 <div class="field"><label>Search</label><input class="control" id="q" placeholder="Name, role or skill"></div>
 <div class="field"><label>Applied job</label><select class="control" id="job"><option value="">All jobs</option><?php $roles=array_unique(array_map(fn($x)=>trim($x['role']??''),$items));natcasesort($roles);foreach($roles as $role):if($role==='')continue;?><option><?=htmlspecialchars($role)?></option><?php endforeach?></select></div>
 <div class="field"><label>Skill</label><select class="control" id="skill"><option value="">All skills</option><?php foreach($skills as $key=>$label):?><option value="<?=htmlspecialchars($key)?>"><?=htmlspecialchars($label)?></option><?php endforeach?></select></div>
 <div class="field"><label>Minimum experience</label><select class="control" id="experience"><option value="0">Any experience</option><option value="12">1+ year</option><option value="36">3+ years</option><option value="60">5+ years</option><option value="96">8+ years</option></select></div>
 <div class="field"><label>Source</label><select class="control" id="source"><option value="">All sources</option><?php foreach(array_unique(array_column($items,'source')) as $s):?><option><?=htmlspecialchars($s)?></option><?php endforeach?></select></div>
 <div class="field"><label>Minimum score</label><select class="control" id="score"><option value="0">Any score</option><option value="1">Analyzed only</option><option value="50">50%+</option><option value="70">70%+</option></select></div>
 <div class="field"><label>Stage</label><select class="control" id="stage"><option value="">All stages</option><?php foreach(['Applied','Screening','Interview','Offer','Rejected'] as $s):?><option><?=$s?></option><?php endforeach?></select></div>
</aside><article class="panel candidate-list"><div id="count" style="padding:5px 0 12px;font-size:9px;color:var(--muted)"><?=count($items)?> records</div>
<?php foreach($items as $c):$d=candidatePresentation($c);$candidateSkills=array_values(array_filter(array_map('trim',$c['skills']??[])));$months=(int)($c['experience']['total_months']??0);$initials=implode('',array_map(fn($x)=>mb_substr($x,0,1),array_slice(preg_split('/\s+/',trim($d['name'])),0,2)));?>
<a class="candidate-row" href="candidate_detail.php?id=<?=urlencode($c['id'])?>" data-find="<?=htmlspecialchars(mb_strtolower($d['name'].' '.$d['role'].' '.implode(' ',$candidateSkills)))?>" data-job="<?=htmlspecialchars(trim($d['role']))?>" data-country="<?=htmlspecialchars($c['country_code']??'')?>" data-skills="<?=htmlspecialchars('|'.mb_strtolower(implode('|',$candidateSkills)).'|')?>" data-months="<?=$months?>" data-source="<?=htmlspecialchars($c['source']??'')?>" data-score="<?=(int)$c['score']?>" data-stage="<?=htmlspecialchars($c['stage']??'Applied')?>"><span class="avatar-sm"><?=htmlspecialchars($initials?:'--')?></span><div><strong><?=htmlspecialchars($d['name'])?></strong><p><?=htmlspecialchars($d['role'])?> · <?=htmlspecialchars($c['source']??'Unknown')?> · <?=htmlspecialchars($c['stage']??'Applied')?></p><?php foreach(array_slice($candidateSkills,0,4) as $itemSkill):?><span class="tag"><?=htmlspecialchars($itemSkill)?></span><?php endforeach?></div><div class="row-meta"><b><?=(int)$c['score']?>%</b><span><?=$months?round($months/12,1).' years':'Experience unavailable'?></span></div></a>
<?php endforeach?><div class="empty" id="empty" style="display:none">No matching candidates.</div></article></section>
<script>
const rows=[...document.querySelectorAll('.candidate-row')],q=document.getElementById('q'),job=document.getElementById('job'),skill=document.getElementById('skill'),experience=document.getElementById('experience'),source=document.getElementById('source'),score=document.getElementById('score'),stage=document.getElementById('stage'),count=document.getElementById('count'),empty=document.getElementById('empty');
const params=new URLSearchParams(location.search); if(params.get('min'))score.value=params.get('min'); if(params.get('stage'))stage.value=params.get('stage'); if(params.get('job'))job.value=params.get('job');
function filter(){let n=0,country=params.get('country')||'';rows.forEach(r=>{const ok=(!q.value||r.dataset.find.includes(q.value.toLowerCase()))&&(!job.value||r.dataset.job===job.value)&&(!country||r.dataset.country===country)&&(!skill.value||r.dataset.skills.includes('|'+skill.value.toLowerCase()+'|'))&&+r.dataset.months>=+experience.value&&(!source.value||r.dataset.source===source.value)&&+r.dataset.score>=+score.value&&(!stage.value||r.dataset.stage===stage.value);r.style.display=ok?'grid':'none';if(ok)n++});count.textContent=n+' records';empty.style.display=n?'none':'block'}
[q,job,skill,experience,source,score,stage].forEach(x=>x.oninput=filter);filter();
</script>
