<?php
require_once __DIR__.'/lib/auth.php';requireAuth();require_once __DIR__.'/lib/integrations.php';require_once __DIR__.'/lib/email_api_mailer.php';require_once __DIR__.'/lib/smtp_mailer.php';require_once __DIR__.'/lib/interview_email_template.php';
if($_SERVER['REQUEST_METHOD']!=='POST'||!verifyCsrf($_POST['csrf']??'')){http_response_code(403);exit('Invalid request.');}
$pdo=db();$user=currentUser();$batchId=(int)($_POST['batch_id']??0);$candidateId=trim((string)($_POST['candidate_id']??''));$action=(string)($_POST['action']??'');
$batchStmt=$pdo->prepare("SELECT eb.*,wp.job_id,j.title job_title FROM email_batches eb LEFT JOIN wishlist_profiles wp ON wp.id=eb.profile_id LEFT JOIN jobs j ON j.id=wp.job_id WHERE eb.id=? AND eb.user_id=? LIMIT 1");$batchStmt->execute([$batchId,$user['id']]);$batch=$batchStmt->fetch();if(!$batch){http_response_code(404);exit('Batch not found.');}
$audit=$pdo->prepare('INSERT INTO audit_events(user_id,action,entity_type,entity_id,metadata_json) VALUES(?,?,?,?,?)');
try{
 if($action==='resend'){
  $recipientStmt=$pdo->prepare("SELECT er.*,c.name FROM email_recipients er JOIN candidates c ON c.id=er.candidate_id WHERE er.batch_id=? AND er.candidate_id=? AND er.status='failed' LIMIT 1");$recipientStmt->execute([$batchId,$candidateId]);$recipient=$recipientStmt->fetch();if(!$recipient)throw new RuntimeException('Only a failed delivery can be resent.');
  $emailApi=integrationConfig('email_api');if(($emailApi['status']??'')!=='configured')$emailApi=['status'=>'configured','url'=>'https://hrms-api.nonceblox.com/api/emails/send-multi-recipient'];$smtp=integrationConfig('smtp');$date=$batch['interview_at']?date('Y-m-d',strtotime($batch['interview_at'])):'Schedule pending';$time=$batch['interview_at']?date('H:i',strtotime($batch['interview_at'])):'Schedule pending';$html=noncebloxInterviewEmailHtml($recipient['name'],$batch['job_title']?:'Interview',$date,$time,$batch['timezone']?:'Asia/Kolkata');
  $testing=integrationConfig('email_testing');$testEnabled=!array_key_exists('enabled',$testing)||!empty($testing['enabled']);$testEmail=trim((string)($testing['email']??'kishan.sharma@nonceblox.com'));$targets=[$recipient['email']];if($testEnabled&&filter_var($testEmail,FILTER_VALIDATE_EMAIL)&&strcasecmp($testEmail,$recipient['email'])!==0)array_unshift($targets,$testEmail);
  if(!empty($emailApi['url'])){foreach($targets as $target)emailApiSendHtml($emailApi,[$target],$target===$recipient['email']?$batch['subject']:'[TEST COPY] '.$batch['subject'],$html);}elseif(($smtp['status']??'')==='configured'){foreach($targets as $target)smtpSendHtml($smtp,$target,$target===$recipient['email']?$batch['subject']:'[TEST COPY] '.$batch['subject'],$html);}else throw new RuntimeException('Email delivery is not configured.');
  $pdo->beginTransaction();$pdo->prepare("UPDATE email_recipients SET status='sent',sent_at=NOW(),error_text=NULL WHERE id=?")->execute([$recipient['id']]);$pdo->prepare("UPDATE candidates SET stage='Interview' WHERE id=? AND job_id=?")->execute([$candidateId,$batch['job_id']]);$pdo->prepare("INSERT INTO interview_invite_locks(profile_id,candidate_id,batch_id,active,locked_at,reset_at,reset_by) VALUES(?,?,?,1,NOW(),NULL,NULL) ON DUPLICATE KEY UPDATE batch_id=VALUES(batch_id),active=1,locked_at=NOW(),reset_at=NULL,reset_by=NULL")->execute([$batch['profile_id'],$candidateId,$batchId]);$counts=$pdo->prepare("SELECT COUNT(*) total,SUM(status='sent') sent,SUM(status='failed') failed FROM email_recipients WHERE batch_id=?");$counts->execute([$batchId]);$count=$counts->fetch();$status=(int)$count['sent']===(int)$count['total']?'sent':((int)$count['sent']?'partial':'failed');$pdo->prepare('UPDATE email_batches SET status=? WHERE id=?')->execute([$status,$batchId]);$audit->execute([$user['id'],'interview.invitation_resent','candidate',$candidateId,json_encode(['batch_id'=>$batchId,'job_id'=>$batch['job_id'],'outcome'=>'success'])]);$pdo->commit();
 }
 elseif($action==='reset'||$action==='reset_batch'){
  $ids=$action==='reset_batch'?$pdo->prepare('SELECT candidate_id FROM email_recipients WHERE batch_id=?'):$pdo->prepare('SELECT candidate_id FROM email_recipients WHERE batch_id=? AND candidate_id=?');$ids->execute($action==='reset_batch'?[$batchId]:[$batchId,$candidateId]);$candidateIds=$ids->fetchAll(PDO::FETCH_COLUMN);if(!$candidateIds)throw new RuntimeException('No candidates found to reset.');
  $pdo->beginTransaction();$unlock=$pdo->prepare('UPDATE interview_invite_locks SET active=0,reset_at=NOW(),reset_by=? WHERE profile_id=? AND candidate_id=? AND active=1');$stage=$pdo->prepare("UPDATE candidates SET stage='Applied' WHERE id=? AND job_id=? AND stage='Interview'");$cancel=$pdo->prepare("UPDATE interview_invitations ii LEFT JOIN interview_slots s ON s.id=ii.confirmed_slot_id SET s.status=IF(s.id IS NULL,s.status,'available'),s.invitation_id=NULL,s.reserved_at=NULL,ii.status='cancelled',ii.confirmed_slot_id=NULL WHERE ii.email_recipient_id=(SELECT id FROM email_recipients WHERE batch_id=? AND candidate_id=? LIMIT 1)");foreach($candidateIds as $id){$unlock->execute([$user['id'],$batch['profile_id'],$id]);$stage->execute([$id,$batch['job_id']]);$cancel->execute([$batchId,$id]);$audit->execute([$user['id'],'interview.invitation_reset','candidate',$id,json_encode(['batch_id'=>$batchId,'job_id'=>$batch['job_id'],'outcome'=>'success'])]);}$pdo->commit();
 }
 else throw new RuntimeException('Unsupported action.');
 header('Location: interview_batch.php?id='.$batchId.'&action_done='.rawurlencode($action));exit;
}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();header('Location: interview_batch.php?id='.$batchId.'&error='.rawurlencode($e->getMessage()));exit;}
