<?php
require_once __DIR__.'/lib/auth.php';requireAuth();require_once __DIR__.'/lib/workspace.php';require_once __DIR__.'/lib/branding.php';require_once __DIR__.'/lib/integrations.php';require_once __DIR__.'/lib/smtp_mailer.php';
$pdo=db();$user=currentUser();$brand=organizationBrand();$jobId=(int)($_GET['job_id']??$_POST['job_id']??0);$message='';$error='';
$jobStmt=$pdo->prepare('SELECT * FROM jobs WHERE id=?');$jobStmt->execute([$jobId]);$job=$jobStmt->fetch();if(!$job){http_response_code(404);exit('Job not found.');}
$profileStmt=$pdo->prepare('SELECT * FROM wishlist_profiles WHERE job_id=? AND user_id=? ORDER BY id LIMIT 1');$profileStmt->execute([$jobId,$user['id']]);$profile=$profileStmt->fetch();if(!$profile){http_response_code(409);exit('Save favourites for this job before creating interview invitations.');}
$all=array_values(array_filter(loadCandidateRecords(),fn($candidate)=>(int)($candidate['job_id']??0)===$jobId));usort($all,fn($a,$b)=>(int)$b['job_match']['analyzed']<=>(int)$a['job_match']['analyzed']?:(($b['score']??-1)<=>($a['score']??-1)));
$wishStmt=$pdo->prepare("SELECT candidate_id FROM wishlist_items WHERE profile_id=? AND disposition='wishlist'");$wishStmt->execute([$profile['id']]);$preselected=array_flip(array_column($wishStmt->fetchAll(),'candidate_id'));
$smtp=integrationConfig('smtp');$smtpReady=($smtp['status']??'')==='configured'&&!empty($smtp['host'])&&!empty($smtp['from_email']);
if($_SERVER['REQUEST_METHOD']==='POST'&&verifyCsrf($_POST['csrf']??'')){
    try{
        if(($_POST['action']??'')!=='send')throw new RuntimeException('Invalid action.');if(!$smtpReady)throw new RuntimeException('Configure SMTP before sending interview invitations.');
        $ids=array_values(array_unique(array_filter(array_map('strval',$_POST['candidate_ids']??[]))));$subject=trim((string)($_POST['subject']??''));$body=trim((string)($_POST['body']??''));$date=trim((string)($_POST['interview_date']??''));$time=trim((string)($_POST['interview_time']??''));$timezone=trim((string)($_POST['timezone']??'Asia/Kolkata'));if(!$ids||$subject===''||$body===''||$date===''||$time==='')throw new RuntimeException('Select recipients and complete the interview schedule.');
        $marks=implode(',',array_fill(0,count($ids),'?'));$recipientStmt=$pdo->prepare("SELECT id,name,email FROM candidates WHERE job_id=? AND id IN ($marks) AND email IS NOT NULL AND email<>''");$recipientStmt->execute(array_merge([$jobId],$ids));$recipients=$recipientStmt->fetchAll();if(count($recipients)!==count($ids))throw new RuntimeException('Every selected candidate must belong to this job and have a valid email.');
        sort($ids);$interviewAt=$date.' '.$time.':00';$dedupe=hash('sha256',$user['id'].'|'.$jobId.'|'.$subject.'|'.$body.'|'.$interviewAt.'|'.$timezone.'|'.implode(',',$ids));$domain=trim((string)($brand['domain']??''))?:($_SERVER['HTTP_HOST']??'ResumeIQ');
        $pdo->beginTransaction();$pdo->prepare("INSERT INTO email_batches(user_id,profile_id,subject,body,interview_at,timezone,recipient_count,status,dedupe_key) VALUES(?,?,?,?,?,?,?,'sending',?)")->execute([$user['id'],$profile['id'],$subject,$body,$interviewAt,$timezone,count($recipients),$dedupe]);$batchId=(int)$pdo->lastInsertId();$insertRecipient=$pdo->prepare("INSERT INTO email_recipients(batch_id,candidate_id,email,status) VALUES(?,?,?,'pending')");foreach($recipients as $recipient)$insertRecipient->execute([$batchId,$recipient['id'],$recipient['email']]);$pdo->commit();
        $sent=0;$failed=0;$updateRecipient=$pdo->prepare('UPDATE email_recipients SET status=?,sent_at=?,error_text=? WHERE batch_id=? AND candidate_id=?');$move=$pdo->prepare("UPDATE candidates SET stage='Interview' WHERE id=? AND job_id=?");$audit=$pdo->prepare('INSERT INTO audit_events(user_id,action,entity_type,entity_id,metadata_json) VALUES(?,?,?,?,?)');
        foreach($recipients as $recipient){$personal=str_replace(['{{candidate_name}}','{{job_title}}','{{interview_date}}','{{interview_time}}','{{timezone}}'],[$recipient['name'],$job['title'],$date,$time,$timezone],$body);$html=interviewEmailHtml($brand['name']?:'ResumeIQ',$domain,$personal);try{smtpSendHtml($smtp,$recipient['email'],$subject,$html);$updateRecipient->execute(['sent',date('Y-m-d H:i:s'),null,$batchId,$recipient['id']]);$move->execute([$recipient['id'],$jobId]);$audit->execute([$user['id'],'interview.invitation_sent','candidate',$recipient['id'],json_encode(['batch_id'=>$batchId,'job_id'=>$jobId,'interview_at'=>$interviewAt,'timezone'=>$timezone,'outcome'=>'success'])]);$sent++;}catch(Throwable $sendError){$updateRecipient->execute(['failed',null,'Delivery failed.',$batchId,$recipient['id']]);$audit->execute([$user['id'],'interview.invitation_failed','candidate',$recipient['id'],json_encode(['batch_id'=>$batchId,'job_id'=>$jobId,'outcome'=>'failed'])]);$failed++;}}
        $status=$failed===0?'sent':($sent?'partial':'failed');$pdo->prepare('UPDATE email_batches SET status=? WHERE id=?')->execute([$status,$batchId]);$audit->execute([$user['id'],'interview.batch_completed','email_batch',(string)$batchId,json_encode(['job_id'=>$jobId,'sent'=>$sent,'failed'=>$failed,'outcome'=>$status])]);$message=$sent.' invitation'.($sent===1?'':'s').' sent. '.$failed.' failed. Successful recipients moved to Interview.';
    }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error=str_contains($e->getMessage(),'Duplicate entry')?'This exact invitation batch was already sent or started.':$e->getMessage();}
}
$historyStmt=$pdo->prepare("SELECT eb.id,eb.created_at,eb.interview_at,eb.status,eb.recipient_count,SUM(er.status='sent') sent_count FROM email_batches eb LEFT JOIN email_recipients er ON er.batch_id=eb.id WHERE eb.profile_id=? GROUP BY eb.id ORDER BY eb.created_at DESC LIMIT 8");$historyStmt->execute([$profile['id']]);$history=$historyStmt->fetchAll();
$activePage='wishlist';$pageTitle='Interview invitations · ResumeIQ';$pageStyles='<style>.invite-head{padding:20px;display:flex;justify-content:space-between;align-items:center}.invite-grid{display:grid;grid-template-columns:minmax(380px,.9fr) minmax(480px,1.1fr);gap:10px;margin-top:10px}.invite-box{padding:18px}.candidate-search{margin:10px 0}.recipient-list{max-height:510px;overflow:auto;border-top:1px solid var(--line)}.recipient{display:grid;grid-template-columns:25px 32px 1fr auto;gap:9px;align-items:center;padding:11px 4px;border-bottom:1px solid var(--line)}.recipient.hide{display:none}.recipient strong,.recipient small{display:block}.recipient small{color:var(--muted)}.rank-badge{color:var(--primary);font-weight:800;font-size:9px}.score-badge{font-size:12px;color:var(--primary);font-weight:800}.compose label{display:block;font-size:9px;font-weight:700;margin:11px 0 5px}.pair{display:grid;grid-template-columns:1fr 1fr;gap:8px}.compose textarea{min-height:180px;line-height:1.6}.send-row{display:flex;justify-content:space-between;align-items:center;margin-top:13px}.send-row .btn{height:42px}.history{margin-top:10px;padding:18px}.history-row{display:grid;grid-template-columns:1fr 130px 100px;gap:9px;padding:10px 0;border-bottom:1px solid var(--line);font-size:10px}.smtp-warning{padding:11px;background:#fff5e7;color:#8c610d;border-radius:8px}.ok,.err{padding:11px;margin-top:10px;border-radius:8px}.ok{background:var(--green-soft);color:var(--green)}.err{background:#fff1f3;color:var(--danger)}@media(max-width:950px){.invite-grid{grid-template-columns:1fr}}@media(max-width:560px){.pair,.history-row{grid-template-columns:1fr}}</style>';require __DIR__.'/views/partials/header.php';
?>
<section class="panel invite-head"><div><div class="kicker"><i class="fa-solid fa-calendar-check"></i> Interview outreach</div><h1><?=htmlspecialchars(trim($job['title']))?></h1><p class="muted">Choose ranked candidates, review the schedule, then send explicitly.</p></div><a class="btn" href="pipeline.php?job_id=<?=$jobId?>">Open job pipeline</a></section><?php if($message):?><div class="ok"><?=htmlspecialchars($message)?></div><?php endif?><?php if($error):?><div class="err"><?=htmlspecialchars($error)?></div><?php endif?><?php if(!$smtpReady):?><div class="smtp-warning">SMTP is not ready. <a href="integrations.php">Configure email delivery</a> before sending.</div><?php endif?>
<form method="post" class="invite-grid" id="inviteForm"><input type="hidden" name="csrf" value="<?=csrfToken()?>"><input type="hidden" name="action" value="send"><input type="hidden" name="job_id" value="<?=$jobId?>"><section class="panel invite-box"><h2>Recipients</h2><input class="control candidate-search" id="candidateSearch" placeholder="Search name, email, role or skill"><div class="recipient-list"><?php foreach($all as $index=>$candidate):$person=candidatePresentation($candidate);?><label class="recipient" data-find="<?=htmlspecialchars(mb_strtolower($person['name'].' '.$candidate['email'].' '.$person['role'].' '.implode(' ',$candidate['skills']??[])))?>"><input type="checkbox" name="candidate_ids[]" value="<?=htmlspecialchars($candidate['id'])?>" <?=isset($preselected[$candidate['id']])?'checked':''?> <?=empty($candidate['email'])?'disabled':''?>><span class="rank-badge">#<?=$index+1?></span><span><strong><?=htmlspecialchars($person['name'])?></strong><small><?=htmlspecialchars($candidate['email']?:'Email unavailable')?> · <?=htmlspecialchars($person['role'])?></small></span><span class="score-badge"><?=$candidate['job_match']['analyzed']?$candidate['score'].'%':'—'?></span></label><?php endforeach?></div></section><section class="panel invite-box compose"><h2>Invitation</h2><div id="recipientSummary" class="tag">0 selected</div><label>Subject</label><input class="control" name="subject" value="Interview invitation — <?=htmlspecialchars(trim($job['title']))?>" required><div class="pair"><div><label>Date</label><input class="control" type="date" name="interview_date" required></div><div><label>Time</label><input class="control" type="time" name="interview_time" required></div></div><label>Timezone</label><select class="control" name="timezone"><option>Asia/Kolkata</option><option>UTC</option></select><label>Message</label><textarea class="control" name="body" required>Hello {{candidate_name}},

Thank you for your interest in the {{job_title}} role. We would like to invite you for an interview on {{interview_date}} at {{interview_time}} ({{timezone}}).

Please reply to confirm your availability.

Regards,
Hiring Team</textarea><div class="send-row"><small class="muted">Only successful deliveries move candidates to Interview.</small><button class="btn btn-primary" <?=$smtpReady?'':'disabled'?> onclick="return confirm('Send this interview invitation to the selected candidates?')"><i class="fa-solid fa-paper-plane"></i> Send invitations</button></div></section></form>
<section class="panel history"><h2>Recent interview outreach</h2><?php foreach($history as $batch):?><div class="history-row"><span><strong>Batch #<?=$batch['id']?></strong><br><small><?=htmlspecialchars($batch['created_at'])?></small></span><span><?=htmlspecialchars($batch['interview_at']?:'Schedule unavailable')?></span><span class="tag"><?=htmlspecialchars($batch['status'])?> · <?=(int)$batch['sent_count']?>/<?=(int)$batch['recipient_count']?></span></div><?php endforeach?><?php if(!$history):?><p class="muted">No interview invitation batches yet.</p><?php endif?></section>
<script>const rows=[...document.querySelectorAll('.recipient')],search=document.getElementById('candidateSearch'),boxes=[...document.querySelectorAll('.recipient input[type="checkbox"]')],summary=document.getElementById('recipientSummary');function updateSummary(){summary.textContent=boxes.filter(box=>box.checked).length+' selected'}search.oninput=()=>{const query=search.value.trim().toLowerCase();rows.forEach(row=>row.classList.toggle('hide',query&&!row.dataset.find.includes(query)))};boxes.forEach(box=>box.addEventListener('change',updateSummary));updateSummary();</script>
<?php require __DIR__.'/views/partials/footer.php';
