<?php
require_once __DIR__.'/lib/auth.php';requireAuth();$pdo=db();$user=currentUser();
$jobId=(int)($_GET['job_id']??0);$status=trim((string)($_GET['status']??'all'));$allowed=['all','confirmed','awaiting_confirmation','completed'];if(!in_array($status,$allowed,true))$status='all';
$jobs=$pdo->prepare('SELECT DISTINCT j.id,j.title FROM interview_batches ib JOIN jobs j ON j.id=ib.job_id WHERE ib.created_by=? ORDER BY j.title');$jobs->execute([$user['id']]);$jobs=$jobs->fetchAll();
$params=[$user['id']];$where='';if($jobId){$where.=' AND ib.job_id=?';$params[]=$jobId;}if($status==='confirmed')$where.=" AND ii.status='confirmed' AND ii.outcome IS NULL";elseif($status==='awaiting_confirmation')$where.=" AND ii.status='awaiting_confirmation'";elseif($status==='completed')$where.=' AND ii.outcome IS NOT NULL';
$stmt=$pdo->prepare("SELECT ii.id,ii.status,ii.recipient_email,ii.notification_status,ii.outcome,ii.outcome_notes,c.name candidate_name,j.title job_title,ib.availability_start,ib.availability_end,ib.timezone,s.starts_at FROM interview_invitations ii JOIN interview_batches ib ON ib.id=ii.batch_id JOIN candidates c ON c.id=ii.candidate_id JOIN jobs j ON j.id=ib.job_id LEFT JOIN interview_slots s ON s.id=ii.confirmed_slot_id WHERE ib.created_by=?$where ORDER BY COALESCE(s.starts_at,CONCAT(ib.availability_start,' 23:59:59')),c.name");$stmt->execute($params);$items=$stmt->fetchAll();
$confirmed=array_values(array_filter($items,fn($x)=>$x['status']==='confirmed'&&!$x['outcome']));$waiting=array_values(array_filter($items,fn($x)=>$x['status']==='awaiting_confirmation'));$decided=array_values(array_filter($items,fn($x)=>!empty($x['outcome'])));$byDate=[];foreach($confirmed as $item)$byDate[substr($item['starts_at'],0,10)][]=$item;
$labels=['completed'=>'Completed','no_show'=>'No show','selected'=>'Selected','rejected'=>'Rejected','offer_sent'=>'Offer sent','offer_accepted'=>'Offer accepted','offer_declined'=>'Offer declined','hired'=>'Hired'];$activePage='calendar';$pageTitle='Interview calendar · ResumeIQ';
$pageStyles='<style>.calendar-head{padding:22px;display:flex;justify-content:space-between;gap:16px;align-items:center}.filters{display:flex;gap:8px}.calendar-grid{display:grid;grid-template-columns:1.3fr .7fr;gap:10px;margin-top:10px}.calendar-panel{padding:18px}.date-group{margin-top:16px}.date-group h3{font-size:11px;color:var(--muted);text-transform:uppercase}.meeting,.waiting,.decision{border:1px solid var(--line);border-radius:9px;padding:13px;margin-top:8px}.meeting{border-left:4px solid var(--primary)}.item-head{display:flex;justify-content:space-between;gap:10px}.item-copy small,.waiting small,.decision small{display:block;color:var(--muted);margin-top:4px}.outcome-form{display:grid;grid-template-columns:150px 1fr auto;gap:7px;margin-top:11px}.badge{padding:5px 8px;border-radius:7px;background:var(--primary-soft);color:var(--primary);font-size:9px;font-weight:700}.badge.failed{background:#fff1f3;color:var(--danger)}.stack{max-height:720px;overflow:auto}.decision{border-left:4px solid var(--green)}.notice{padding:10px;margin-top:10px;background:var(--green-soft);color:var(--green)}@media(max-width:950px){.calendar-grid{grid-template-columns:1fr}.filters,.outcome-form{grid-template-columns:1fr;display:grid}.calendar-head{align-items:flex-start;flex-direction:column}}</style>';require __DIR__.'/views/partials/header.php';
?>
<section class="panel calendar-head"><div><div class="kicker"><i class="fa-regular fa-calendar-check"></i> Interview workflow</div><h1>Interview calendar</h1><p>Confirmed meetings, pending replies, notification health, and recruiter-controlled outcomes.</p></div><form class="filters"><select class="control" name="job_id"><option value="0">All job profiles</option><?php foreach($jobs as $job):?><option value="<?=(int)$job['id']?>" <?=(int)$job['id']===$jobId?'selected':''?>><?=htmlspecialchars($job['title'])?></option><?php endforeach?></select><select class="control" name="status"><option value="all">All statuses</option><option value="confirmed" <?=$status==='confirmed'?'selected':''?>>Upcoming</option><option value="awaiting_confirmation" <?=$status==='awaiting_confirmation'?'selected':''?>>Awaiting</option><option value="completed" <?=$status==='completed'?'selected':''?>>Decided</option></select><button class="btn" type="submit">Apply</button></form></section>
<?php if(isset($_GET['updated'])):?><div class="notice">Interview outcome saved and pipeline stage updated.</div><?php endif?>
<section class="calendar-grid"><article class="panel calendar-panel"><h2>Upcoming <span class="badge"><?=count($confirmed)?> confirmed</span></h2><?php foreach($byDate as $date=>$meetings):?><section class="date-group"><h3><?=htmlspecialchars(date('l, d F Y',strtotime($date)))?></h3><?php foreach($meetings as $meeting):?><div class="meeting"><div class="item-head"><div class="item-copy"><strong><?=htmlspecialchars(date('g:i A',strtotime($meeting['starts_at'])))?> · <?=htmlspecialchars($meeting['candidate_name'])?></strong><small><?=htmlspecialchars($meeting['job_title'])?> · <?=htmlspecialchars($meeting['recipient_email'])?> · <?=htmlspecialchars($meeting['timezone'])?></small></div><span class="badge <?=$meeting['notification_status']==='failed'?'failed':''?>">Mail <?=htmlspecialchars($meeting['notification_status']?:'not sent')?></span></div><?php if($meeting['notification_status']==='failed'):?><form method="post" action="interview_confirmation_retry.php" style="margin-top:10px"><input type="hidden" name="csrf" value="<?=htmlspecialchars(csrfToken())?>"><input type="hidden" name="invitation_id" value="<?=(int)$meeting['id']?>"><button class="btn" type="submit">Retry confirmation email</button></form><?php endif?><form class="outcome-form" method="post" action="interview_outcome.php"><input type="hidden" name="csrf" value="<?=htmlspecialchars(csrfToken())?>"><input type="hidden" name="invitation_id" value="<?=(int)$meeting['id']?>"><select class="control" name="outcome" required><option value="">Set outcome</option><?php foreach($labels as $value=>$label):?><option value="<?=$value?>"><?=$label?></option><?php endforeach?></select><input class="control" name="notes" maxlength="1000" placeholder="Optional recruiter note"><button class="btn btn-primary" type="submit">Save</button></form></div><?php endforeach?></section><?php endforeach?><?php if(!$confirmed):?><div class="empty">No upcoming confirmed interviews for this filter.</div><?php endif?></article>
<aside class="panel calendar-panel stack"><h2>Awaiting reply <span class="badge"><?=count($waiting)?></span></h2><?php foreach($waiting as $item):?><div class="waiting"><strong><?=htmlspecialchars($item['candidate_name'])?></strong><small><?=htmlspecialchars($item['job_title'])?></small><small>Window <?=htmlspecialchars(date('d M',strtotime($item['availability_start'])))?>–<?=htmlspecialchars(date('d M Y',strtotime($item['availability_end'])))?></small></div><?php endforeach?><?php if(!$waiting):?><div class="empty">No candidates awaiting confirmation.</div><?php endif?><h2 style="margin-top:24px">Outcome history <span class="badge"><?=count($decided)?></span></h2><?php foreach($decided as $item):?><div class="decision"><strong><?=htmlspecialchars($item['candidate_name'])?></strong><small><?=htmlspecialchars($item['job_title'])?> · <?=htmlspecialchars($labels[$item['outcome']]??$item['outcome'])?></small><?php if($item['outcome_notes']):?><small><?=htmlspecialchars($item['outcome_notes'])?></small><?php endif?></div><?php endforeach?><?php if(!$decided):?><div class="empty">No interview outcomes recorded.</div><?php endif?></aside></section>
<script src=assets/interview-calendar-actions.js></script>
<?php require __DIR__.'/views/partials/footer.php';
