<?php
require_once __DIR__.'/lib/auth.php';requireAuth();require_once __DIR__.'/lib/workspace.php';require_once __DIR__.'/lib/branding.php';require_once __DIR__.'/lib/integrations.php';require_once __DIR__.'/lib/smtp_mailer.php';require_once __DIR__.'/lib/email_api_mailer.php';require_once __DIR__.'/lib/interview_email_template.php';require_once __DIR__.'/lib/interview_schedule.php';require_once __DIR__.'/lib/interview_schedule_persistence.php';require_once __DIR__.'/lib/interview_send_bridge.php';
$pdo=db();$user=currentUser();$brand=organizationBrand();$jobId=(int)($_GET['job_id']??$_POST['job_id']??0);$message='';$error='';
$jobStmt=$pdo->prepare('SELECT * FROM jobs WHERE id=?');$jobStmt->execute([$jobId]);$job=$jobStmt->fetch();if(!$job){http_response_code(404);exit('Job not found.');}
$profileStmt=$pdo->prepare('SELECT * FROM wishlist_profiles WHERE job_id=? AND user_id=? ORDER BY id LIMIT 1');$profileStmt->execute([$jobId,$user['id']]);$profile=$profileStmt->fetch();if(!$profile){http_response_code(409);exit('Save favourites for this job before creating interview invitations.');}
$profileOptionsStmt=$pdo->prepare('SELECT wp.job_id,j.title,COUNT(CASE WHEN wi.disposition=\'wishlist\' THEN 1 END) favourite_count FROM wishlist_profiles wp JOIN jobs j ON j.id=wp.job_id LEFT JOIN wishlist_items wi ON wi.profile_id=wp.id WHERE wp.user_id=? GROUP BY wp.id,wp.job_id,j.title ORDER BY j.title');$profileOptionsStmt->execute([$user['id']]);$profileOptions=$profileOptionsStmt->fetchAll();
$all=array_values(array_filter(loadCandidateRecords(),fn($candidate)=>(int)($candidate['job_id']??0)===$jobId));usort($all,fn($a,$b)=>(int)$b['job_match']['analyzed']<=>(int)$a['job_match']['analyzed']?:(($b['score']??-1)<=>($a['score']??-1)));
$wishStmt=$pdo->prepare("SELECT candidate_id FROM wishlist_items WHERE profile_id=? AND disposition='wishlist'");$wishStmt->execute([$profile['id']]);$preselected=array_flip(array_column($wishStmt->fetchAll(),'candidate_id'));
$lockStmt=$pdo->prepare('SELECT candidate_id FROM interview_invite_locks WHERE profile_id=? AND active=1');$lockStmt->execute([$profile['id']]);$locked=array_fill_keys($lockStmt->fetchAll(PDO::FETCH_COLUMN),true);
$emailApi=integrationConfig('email_api');if(($emailApi['status']??'')!=='configured')$emailApi=['status'=>'configured','url'=>'https://hrms-api.nonceblox.com/api/emails/send-multi-recipient'];$emailApiReady=!empty($emailApi['url']);$smtp=integrationConfig('smtp');$smtpReady=($smtp['status']??'')==='configured'&&!empty($smtp['host'])&&!empty($smtp['from_email']);$deliveryReady=$emailApiReady||$smtpReady;$deliveryName=$emailApiReady?'NonceBlox Email API':'SMTP';$emailTesting=integrationConfig('email_testing');$testCopyEnabled=!array_key_exists('enabled',$emailTesting)||!empty($emailTesting['enabled']);$testCopyEmail=trim((string)($emailTesting['email']??'kishan.sharma@nonceblox.com'));$deliverOne=function(string $to,string $mailSubject,string $html)use($emailApiReady,$emailApi,$smtp){if($emailApiReady)emailApiSendHtml($emailApi,[$to],$mailSubject,$html);else smtpSendHtml($smtp,$to,$mailSubject,$html);};$deliverInterview=function(string $to,string $mailSubject,string $html)use($deliverOne,$testCopyEnabled,$testCopyEmail){if($testCopyEnabled&&filter_var($testCopyEmail,FILTER_VALIDATE_EMAIL)&&strcasecmp($to,$testCopyEmail)!==0)$deliverOne($testCopyEmail,'[TEST COPY] '.$mailSubject,$html);$deliverOne($to,$mailSubject,$html);};
if($_SERVER['REQUEST_METHOD']==='POST'&&($_POST['action']??'')==='reset'&&verifyCsrf($_POST['csrf']??'')){$pdo->prepare('UPDATE interview_invite_locks SET active=0,reset_at=NOW(),reset_by=? WHERE profile_id=? AND active=1')->execute([$user['id'],$profile['id']]);$pdo->prepare("INSERT INTO audit_events(user_id,action,entity_type,entity_id,metadata_json) VALUES(?,'interview.invitation_locks_reset','wishlist_profile',?,?)")->execute([$user['id'],(string)$profile['id'],json_encode(['job_id'=>$jobId,'outcome'=>'success'])]);header('Location: interview_invite.php?job_id='.$jobId);exit;}
require __DIR__.'/lib/interview_invite_scheduler.php';
if($_SERVER['REQUEST_METHOD']==='POST'&&($_POST['action']??'')==='send'&&verifyCsrf($_POST['csrf']??'')){
    try{
        if(($_POST['action']??'')!=='send')throw new RuntimeException('Invalid action.');if(!$deliveryReady)throw new RuntimeException('Configure the NonceBlox Email API or SMTP before sending interview invitations.');
        $ids=array_values(array_unique(array_filter(array_map('strval',$_POST['candidate_ids']??[]))));$subject=trim((string)($_POST['subject']??''));$body=trim((string)($_POST['body']??''));$date=trim((string)($_POST['interview_date']??''));$time=trim((string)($_POST['interview_time']??''));$timezone=trim((string)($_POST['timezone']??'Asia/Kolkata'));if(!$ids||$subject===''||$body===''||$date===''||$time==='')throw new RuntimeException('Select recipients and complete the interview schedule.');
        $marks=implode(',',array_fill(0,count($ids),'?'));$recipientStmt=$pdo->prepare("SELECT c.id,c.name,c.email FROM candidates c WHERE c.job_id=? AND c.id IN ($marks) AND c.email IS NOT NULL AND c.email<>'' AND NOT EXISTS(SELECT 1 FROM interview_invite_locks il WHERE il.profile_id=? AND il.candidate_id=c.id AND il.active=1)");$recipientStmt->execute(array_merge([$jobId],$ids,[$profile['id']]));$recipients=$recipientStmt->fetchAll();if(count($recipients)!==count($ids))throw new RuntimeException('A selected candidate is invalid, has no email, or was already invited. Reset invited candidates before selecting them again.');
        sort($ids);$interviewAt=$date.' '.$time.':00';$dedupe=hash('sha256',$user['id'].'|'.$jobId.'|'.$subject.'|'.$body.'|'.$interviewAt.'|'.$timezone.'|'.implode(',',$ids));$domain=trim((string)($brand['domain']??''))?:($_SERVER['HTTP_HOST']??'ResumeIQ');
        $pdo->beginTransaction();$pdo->prepare("INSERT INTO email_batches(user_id,profile_id,subject,body,interview_at,timezone,recipient_count,status,dedupe_key) VALUES(?,?,?,?,?,?,?,'sending',?)")->execute([$user['id'],$profile['id'],$subject,$body,$interviewAt,$timezone,count($recipients),$dedupe]);$batchId=(int)$pdo->lastInsertId();$insertRecipient=$pdo->prepare("INSERT INTO email_recipients(batch_id,candidate_id,email,status) VALUES(?,?,?,'pending')");foreach($recipients as $recipient)$insertRecipient->execute([$batchId,$recipient['id'],$recipient['email']]);$pdo->commit();
        $sent=0;$failed=0;$updateRecipient=$pdo->prepare('UPDATE email_recipients SET status=?,sent_at=?,error_text=? WHERE batch_id=? AND candidate_id=?');$move=$pdo->prepare("UPDATE candidates SET stage='Interview' WHERE id=? AND job_id=?");$lock=$pdo->prepare('INSERT INTO interview_invite_locks(profile_id,candidate_id,batch_id,active,locked_at,reset_at,reset_by) VALUES(?,?,?,1,NOW(),NULL,NULL) ON DUPLICATE KEY UPDATE batch_id=VALUES(batch_id),active=1,locked_at=NOW(),reset_at=NULL,reset_by=NULL');$audit=$pdo->prepare('INSERT INTO audit_events(user_id,action,entity_type,entity_id,metadata_json) VALUES(?,?,?,?,?)');
        foreach($recipients as $recipient){$html=noncebloxInterviewEmailHtml($recipient['name'],$job['title'],$date,$time,$timezone);try{$deliverInterview($recipient['email'],$subject,$html);$updateRecipient->execute(['sent',date('Y-m-d H:i:s'),null,$batchId,$recipient['id']]);$move->execute([$recipient['id'],$jobId]);$lock->execute([$profile['id'],$recipient['id'],$batchId]);$audit->execute([$user['id'],'interview.invitation_sent','candidate',$recipient['id'],json_encode(['batch_id'=>$batchId,'job_id'=>$jobId,'interview_at'=>$interviewAt,'timezone'=>$timezone,'transport'=>$deliveryName,'template'=>'nonceblox_interview_v1','test_copy'=>$testCopyEnabled?$testCopyEmail:null,'outcome'=>'success'])]);$sent++;}catch(Throwable $sendError){$updateRecipient->execute(['failed',null,'Delivery failed.',$batchId,$recipient['id']]);$audit->execute([$user['id'],'interview.invitation_failed','candidate',$recipient['id'],json_encode(['batch_id'=>$batchId,'job_id'=>$jobId,'transport'=>$deliveryName,'template'=>'nonceblox_interview_v1','test_copy'=>$testCopyEnabled?$testCopyEmail:null,'outcome'=>'failed'])]);$failed++;}}
        $status=$failed===0?'sent':($sent?'partial':'failed');$pdo->prepare('UPDATE email_batches SET status=? WHERE id=?')->execute([$status,$batchId]);$audit->execute([$user['id'],'interview.batch_completed','email_batch',(string)$batchId,json_encode(['job_id'=>$jobId,'sent'=>$sent,'failed'=>$failed,'outcome'=>$status])]);$message=$sent.' invitation'.($sent===1?'':'s').' sent. '.$failed.' failed. Successful recipients moved to Interview.';
    }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error=str_contains($e->getMessage(),'Duplicate entry')?'This exact invitation batch was already sent or started.':$e->getMessage();}
}
$historyStmt=$pdo->prepare("SELECT eb.id,eb.created_at,eb.interview_at,eb.status,eb.recipient_count,SUM(er.status='sent') sent_count FROM email_batches eb LEFT JOIN email_recipients er ON er.batch_id=eb.id WHERE eb.profile_id=? GROUP BY eb.id ORDER BY eb.created_at DESC LIMIT 8");$historyStmt->execute([$profile['id']]);$history=$historyStmt->fetchAll();
$activePage='wishlist';$pageTitle='Interview invitations · ResumeIQ';$pageStyles='<style>.invite-head{padding:20px;display:flex;justify-content:space-between;align-items:center}.invite-grid{display:grid;grid-template-columns:minmax(380px,.9fr) minmax(480px,1.1fr);gap:10px;margin-top:10px}.invite-box{padding:18px}.candidate-search{margin:10px 0}.recipient-list{max-height:510px;overflow:auto;border-top:1px solid var(--line)}.recipient{display:grid;grid-template-columns:25px 32px 1fr auto;gap:9px;align-items:center;padding:11px 4px;border-bottom:1px solid var(--line)}.recipient.hide{display:none}.recipient strong,.recipient small{display:block}.recipient small{color:var(--muted)}.rank-badge{color:var(--primary);font-weight:800;font-size:9px}.score-badge{font-size:12px;color:var(--primary);font-weight:800}.compose label{display:block;font-size:9px;font-weight:700;margin:11px 0 5px}.pair{display:grid;grid-template-columns:1fr 1fr;gap:8px}.compose textarea{min-height:180px;line-height:1.6}.send-row{display:flex;justify-content:space-between;align-items:center;margin-top:13px}.send-row .btn{height:42px}.history{margin-top:10px;padding:18px}.history-row{display:grid;grid-template-columns:1fr 130px 100px;gap:9px;padding:10px 0;border-bottom:1px solid var(--line);font-size:10px}.smtp-warning{padding:11px;background:#fff5e7;color:#8c610d;border-radius:8px}.ok,.err{padding:11px;margin-top:10px;border-radius:8px}.ok{background:var(--green-soft);color:var(--green)}.err{background:#fff1f3;color:var(--danger)}@media(max-width:950px){.invite-grid{grid-template-columns:1fr}}@media(max-width:560px){.pair,.history-row{grid-template-columns:1fr}}</style>';require __DIR__.'/views/partials/header.php';
?>
<section class="panel invite-head"><div><div class="kicker"><i class="fa-solid fa-calendar-check"></i> Interview outreach</div><h1><?=htmlspecialchars(trim($job['title']))?></h1><p class="muted">Choose ranked candidates, review the schedule, then send explicitly.</p></div><a class="btn" href="pipeline.php?job_id=<?=$jobId?>">Open job pipeline</a></section><?php if($message):?><div class="ok"><?=htmlspecialchars($message)?></div><?php endif?><?php if($error):?><div class="err"><?=htmlspecialchars($error)?></div><?php endif?><?php if(!$smtpReady):?><div class="smtp-warning">SMTP is not ready. <a href="integrations.php">Configure email delivery</a> before sending.</div><?php endif?>
<form method="post" class="invite-grid" id="inviteForm"><input type="hidden" name="csrf" value="<?=csrfToken()?>"><input type="hidden" name="action" value="send"><input type="hidden" name="job_id" value="<?=$jobId?>"><section class="panel invite-box"><h2>Recipients</h2><input class="control candidate-search" id="candidateSearch" placeholder="Search name, email, role or skill"><div class="recipient-list"><?php foreach($all as $index=>$candidate):$person=candidatePresentation($candidate);?><label class="recipient" data-find="<?=htmlspecialchars(mb_strtolower($person['name'].' '.$candidate['email'].' '.$person['role'].' '.implode(' ',$candidate['skills']??[])))?>"><input type="checkbox" name="candidate_ids[]" value="<?=htmlspecialchars($candidate['id'])?>" <?=isset($preselected[$candidate['id']])?'checked':''?> <?=empty($candidate['email'])?'disabled':''?>><span class="rank-badge">#<?=$index+1?></span><span><strong><?=htmlspecialchars($person['name'])?></strong><small><?=htmlspecialchars($candidate['email']?:'Email unavailable')?> · <?=htmlspecialchars($person['role'])?></small></span><span class="score-badge"><?=$candidate['job_match']['analyzed']?$candidate['score'].'%':'—'?></span></label><?php endforeach?></div></section><section class="panel invite-box compose"><h2>Invitation</h2><div id="recipientSummary" class="tag">0 selected</div><label>Subject</label><input class="control" name="subject" value="Interview invitation — <?=htmlspecialchars(trim($job['title']))?>" required><div class="pair"><div><label>Date</label><input class="control" type="date" name="interview_date" required></div><div><label>Time</label><input class="control" type="time" name="interview_time" required></div></div><label>Timezone</label><select class="control" name="timezone"><option>Asia/Kolkata</option><option>UTC</option></select><label>Message</label><textarea class="control" name="body" required>Hello {{candidate_name}},

Thank you for your interest in the {{job_title}} role. We would like to invite you for an interview on {{interview_date}} at {{interview_time}} ({{timezone}}).

Please reply to confirm your availability.

Regards,
Hiring Team</textarea><div class="send-row"><small class="muted">Only successful deliveries move candidates to Interview.</small><button class="btn btn-primary" <?=$smtpReady?'':'disabled'?> onclick="return confirm('Send this interview invitation to the selected candidates?')"><i class="fa-solid fa-paper-plane"></i> Send invitations</button></div></section></form>
<section class="panel history"><h2>Recent interview outreach</h2><?php foreach($history as $batch):?><div class="history-row"><span><strong>Batch #<?=$batch['id']?></strong><br><small><?=htmlspecialchars($batch['created_at'])?></small></span><span><?=htmlspecialchars($batch['interview_at']?:'Schedule unavailable')?></span><span class="tag"><?=htmlspecialchars($batch['status'])?> · <?=(int)$batch['sent_count']?>/<?=(int)$batch['recipient_count']?></span></div><?php endforeach?><?php if(!$history):?><p class="muted">No interview invitation batches yet.</p><?php endif?></section>
<script>const rows=[...document.querySelectorAll('.recipient')],search=document.getElementById('candidateSearch'),boxes=[...document.querySelectorAll('.recipient input[type="checkbox"]')],summary=document.getElementById('recipientSummary');function updateSummary(){summary.textContent=boxes.filter(box=>box.checked).length+' selected'}search.oninput=()=>{const query=search.value.trim().toLowerCase();rows.forEach(row=>row.classList.toggle('hide',query&&!row.dataset.find.includes(query)))};boxes.forEach(box=>box.addEventListener('change',updateSummary));updateSummary();</script>
<script>
const lockedIds=<?=json_encode(array_keys($locked))?>;
lockedIds.forEach(id=>{const box=document.querySelector('.recipient input[value="'+CSS.escape(id)+'"]');if(!box)return;box.checked=false;box.disabled=true;const row=box.closest('.recipient');row.style.opacity='.5';row.style.cursor='not-allowed';row.querySelector('.score-badge').textContent='Invited';});
updateSummary();
const headActions=document.querySelector('.invite-head>a')?.parentElement;
if(headActions){headActions.style.display='flex';headActions.style.gap='8px';const reset=document.createElement('form');reset.method='post';reset.onsubmit=()=>confirm('Reset invited candidates for this job and allow selection again?');reset.innerHTML='<input type="hidden" name="csrf" value="<?=csrfToken()?>"><input type="hidden" name="action" value="reset"><input type="hidden" name="job_id" value="<?=$jobId?>"><button class="btn" <?=empty($locked)?'disabled':''?>><i class="fa-solid fa-rotate-left"></i> Reset invited</button>';headActions.prepend(reset);}
const intro=document.querySelector('.invite-head .muted');if(intro)intro.textContent='Saved favourites are preselected. You can add more ranked candidates from this job.';
</script>
<style>
.invite-actions{display:flex;align-items:end;gap:8px;position:relative;z-index:2}.profile-switch{display:grid;gap:4px;font-size:10px;color:var(--muted)}.profile-switch select{min-width:220px}.mail-preview{margin-top:18px;border:1px solid var(--line);border-radius:12px;overflow:hidden;background:#f3f4f8}.preview-toolbar{padding:10px 12px;border-bottom:1px solid var(--line);background:#fff}.preview-recipients{display:flex;flex-wrap:wrap;gap:5px;margin-top:7px}.preview-recipient{padding:4px 7px;border-radius:6px;background:var(--primary-soft);color:var(--primary);font-size:9px}.preview-paper{margin:18px;background:#fff;border:1px solid #e4e3ec;border-radius:10px;overflow:hidden;box-shadow:0 15px 35px #25203d14}.preview-brand{padding:18px 20px;background:linear-gradient(135deg,#faf9ff,#eeeaff)}.preview-brand img{display:block;max-width:115px;max-height:44px}.preview-brand strong{font-size:19px}.preview-subject{padding:15px 20px;border-bottom:1px solid var(--line);font-weight:800}.preview-copy{padding:20px;min-height:170px;white-space:pre-wrap;line-height:1.65}.preview-footer{padding:12px 20px;border-top:1px solid var(--line);color:var(--muted);font-size:10px}@media(max-width:780px){.invite-head{align-items:flex-start;flex-direction:column}.invite-actions{width:100%;flex-wrap:wrap}.profile-switch{width:100%}.profile-switch select{width:100%}}
</style>
<script>
const actionLink=document.querySelector('.invite-head>a'),directReset=document.querySelector('.invite-head>form'),actionBar=document.createElement('div');actionBar.className='invite-actions';
if(actionLink){actionLink.before(actionBar);if(directReset)actionBar.appendChild(directReset);const switcher=document.createElement('label'),profileSelect=document.createElement('select'),profileOptions=<?=json_encode($profileOptions,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT)?>;switcher.className='profile-switch';switcher.append('Job profile');profileSelect.className='control';profileOptions.forEach(item=>profileSelect.add(new Option(item.title+' · '+item.favourite_count+' selected',item.job_id,false,Number(item.job_id)===<?=$jobId?>)));profileSelect.onchange=event=>location.href='interview_invite.php?job_id='+event.target.value;switcher.append(profileSelect);actionBar.append(switcher,actionLink);}
const compose=document.querySelector('.compose'),preview=document.createElement('section');preview.className='mail-preview';preview.innerHTML='<div class="preview-toolbar"><strong>Email preview</strong><div class="preview-recipients" id="previewRecipients"></div></div><article class="preview-paper"><header class="preview-brand" id="previewBrand"></header><div class="preview-subject" id="previewSubject"></div><div class="preview-copy" id="previewCopy"></div><footer class="preview-footer"><?=htmlspecialchars($brand['name']?:'ResumeIQ')?> · <?=htmlspecialchars(trim((string)($brand['domain']??''))?:($_SERVER['HTTP_HOST']??'ResumeIQ'))?></footer></article>';compose.append(preview);
const brandNode=document.getElementById('previewBrand');<?php if(!empty($brand['logo_path'])):?>{const brandImage=document.createElement('img');brandImage.src=<?=json_encode($brand['logo_path'])?>;brandImage.alt=<?=json_encode($brand['name']?:'ResumeIQ')?>;brandNode.replaceChildren(brandImage)}<?php else:?>brandNode.textContent=<?=json_encode($brand['name']?:'ResumeIQ')?>;<?php endif?>
const subjectInput=document.querySelector('[name="subject"]'),bodyInput=document.querySelector('[name="body"]'),dateInput=document.querySelector('[name="interview_date"]'),timeInput=document.querySelector('[name="interview_time"]'),timezoneInput=document.querySelector('[name="timezone"]');
function selectedRows(){return boxes.filter(box=>box.checked&&!box.disabled).map(box=>({box,name:box.closest('.recipient').querySelector('strong').textContent.trim()}))}
function renderInvitePreview(){const selected=selectedRows(),first=selected[0]?.name||'Candidate',date=dateInput.value||'the scheduled date',time=timeInput.value||'the scheduled time',timezone=timezoneInput.value,copy=bodyInput.value.replaceAll('{{candidate_name}}',first).replaceAll('{{job_title}}',<?=json_encode(trim($job['title']))?>).replaceAll('{{interview_date}}',date).replaceAll('{{interview_time}}',time).replaceAll('{{timezone}}',timezone);document.getElementById('previewSubject').textContent=subjectInput.value||'Interview invitation';document.getElementById('previewCopy').textContent=copy;document.getElementById('previewRecipients').innerHTML=selected.length?selected.map(item=>'<span class="preview-recipient">'+item.name.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))+'</span>').join(''):'<span class="muted">No recipients selected</span>'}
[subjectInput,bodyInput,dateInput,timeInput,timezoneInput].forEach(input=>input.addEventListener('input',renderInvitePreview));
boxes.forEach(box=>box.addEventListener('change',async()=>{renderInvitePreview();const previous=!box.checked;box.disabled=true;try{const response=await fetch('invite_selection_api.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','Accept':'application/json'},body:new URLSearchParams({csrf:<?=json_encode(csrfToken())?>,job_id:<?=$jobId?>,profile_id:<?=(int)$profile['id']?>,candidate_id:box.value,selected:box.checked?'1':'0'})}),payload=await response.json();if(!response.ok||!payload.ok)throw new Error(payload.error||'Selection could not be saved.')}catch(error){box.checked=previous;alert(error.message)}finally{if(!lockedIds.includes(box.value))box.disabled=false;updateSummary();renderInvitePreview()}}));
renderInvitePreview();
</script>
<style>.mail-preview{position:fixed;inset:0;z-index:120;margin:0;border:0;border-radius:0;background:#17122566;backdrop-filter:blur(4px);display:none;overflow:auto;padding:40px 18px}.mail-preview.open{display:block}.mail-preview>.preview-toolbar,.mail-preview>.preview-paper{width:min(720px,100%);margin-left:auto;margin-right:auto}.mail-preview>.preview-toolbar{border-radius:12px 12px 0 0;display:flex;align-items:center;justify-content:space-between}.mail-preview>.preview-paper{margin-top:0;border-radius:0 0 12px 12px}.preview-open{margin-left:8px}</style>
<script>
const smtpWarning=document.querySelector('.smtp-warning'),sendButton=document.querySelector('.send-row button');if(<?=json_encode($deliveryReady)?>){if(smtpWarning)smtpWarning.hidden=true;if(sendButton)sendButton.disabled=false}else if(smtpWarning)smtpWarning.innerHTML='Email delivery is not ready. <a href="integrations.php">Configure the NonceBlox Email API or SMTP</a> before sending.';
const previewButton=document.createElement('button');previewButton.type='button';previewButton.className='btn preview-open';previewButton.innerHTML='<i class="fa-regular fa-eye"></i> Preview email';summary.after(previewButton);const previewToolbar=preview.querySelector('.preview-toolbar'),previewClose=document.createElement('button');previewClose.type='button';previewClose.className='btn';previewClose.innerHTML='<i class="fa-solid fa-xmark"></i> Close';previewToolbar.append(previewClose);previewButton.onclick=()=>{renderInvitePreview();preview.classList.add('open')};previewClose.onclick=()=>preview.classList.remove('open');preview.addEventListener('click',event=>{if(event.target===preview)preview.classList.remove('open')});document.addEventListener('keydown',event=>{if(event.key==='Escape')preview.classList.remove('open')});
</script>
<style>.template-preview-frame{display:block;width:100%;height:min(76vh,900px);border:0;background:#f6f5f9}.mail-preview>.preview-toolbar{border-radius:12px 12px 0 0}.mail-preview>.template-frame-wrap{width:min(820px,100%);margin:0 auto;border-radius:0 0 12px 12px;overflow:hidden;background:#fff}.compose textarea[name="body"]{display:none}.compose label.template-message-label{display:none}</style>
<script>
const canonicalEmailTemplate=<?=json_encode(file_get_contents(__DIR__.'/assets/interview_email_template.html'),JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT)?>;
const originalMessageLabel=[...compose.querySelectorAll('label')].find(label=>label.textContent.trim()==='Message');if(originalMessageLabel)originalMessageLabel.classList.add('template-message-label');
preview.innerHTML='<div class="preview-toolbar"><div><strong>NonceBlox interview email</strong><div class="preview-recipients" id="previewRecipients"></div></div><button type="button" class="btn" id="canonicalPreviewClose"><i class="fa-solid fa-xmark"></i> Close</button></div><div class="template-frame-wrap"><iframe class="template-preview-frame" id="templatePreviewFrame" title="Interview email preview" sandbox="allow-popups"></iframe></div>';
const canonicalClose=document.getElementById('canonicalPreviewClose'),canonicalFrame=document.getElementById('templatePreviewFrame'),canonicalRecipients=document.getElementById('previewRecipients');
let canonicalPreviewUrl='';function previewEscape(value){const node=document.createElement('span');node.textContent=value;return node.innerHTML}function renderCanonicalPreview(){const selected=selectedRows(),first=selected[0]?.name||'Candidate',date=dateInput.value||'Interview date',time=timeInput.value||'Interview time',timezone=timezoneInput.value||'Asia/Kolkata',html=canonicalEmailTemplate.replaceAll('{{candidate_name}}',previewEscape(first)).replaceAll('{{job_title}}',previewEscape(<?=json_encode(trim($job['title']))?>)).replaceAll('{{interview_date}}',previewEscape(date)).replaceAll('{{interview_time}}',previewEscape(time)).replaceAll('{{timezone}}',previewEscape(timezone));if(canonicalPreviewUrl)URL.revokeObjectURL(canonicalPreviewUrl);canonicalPreviewUrl=URL.createObjectURL(new Blob([html],{type:'text/html;charset=utf-8'}));canonicalFrame.src=canonicalPreviewUrl;canonicalRecipients.textContent=selected.length?selected.map(item=>item.name).join(' · '):'No recipients selected'}
previewButton.onclick=()=>{renderCanonicalPreview();preview.classList.add('open')};canonicalClose.onclick=()=>preview.classList.remove('open');[dateInput,timeInput,timezoneInput].forEach(input=>input.addEventListener('input',renderCanonicalPreview));boxes.forEach(box=>box.addEventListener('change',renderCanonicalPreview));renderCanonicalPreview();
</script>
<link rel=stylesheet href=assets/interview-invite-progress.css><div class=send-lock id=sendLock role=status aria-live=assertive aria-hidden=true><div class=send-lock-card><div class=send-spinner></div><strong>Sending interview invitations...</strong><small>Please keep this page open. Delivery status is being saved.</small></div></div><script src=assets/interview-invite-progress.js></script>
<?php require __DIR__.'/views/partials/footer.php';
