<?php
require_once __DIR__.'/lib/auth.php';requireAuth();
$pdo=db();$user=currentUser();$batchId=(int)($_GET['id']??0);
$batchStmt=$pdo->prepare("SELECT eb.*,wp.job_id,j.title job_title FROM email_batches eb LEFT JOIN wishlist_profiles wp ON wp.id=eb.profile_id LEFT JOIN jobs j ON j.id=wp.job_id WHERE eb.id=? AND eb.user_id=? LIMIT 1");$batchStmt->execute([$batchId,$user['id']]);$batch=$batchStmt->fetch();if(!$batch){http_response_code(404);exit('Interview outreach batch not found.');}
$recipientStmt=$pdo->prepare("SELECT er.candidate_id,er.email,er.status,er.sent_at,er.error_text,c.name,c.role_title,c.stage FROM email_recipients er LEFT JOIN candidates c ON c.id=er.candidate_id WHERE er.batch_id=? ORDER BY FIELD(er.status,'sent','failed','pending'),COALESCE(er.sent_at,'9999-12-31'),c.name");$recipientStmt->execute([$batchId]);$recipients=$recipientStmt->fetchAll();
$pdo->prepare("INSERT INTO audit_events(user_id,action,entity_type,entity_id,metadata_json) VALUES(?,'interview.batch_viewed','email_batch',?,?)")->execute([$user['id'],(string)$batchId,json_encode(['job_id'=>$batch['job_id']??null,'outcome'=>'success'])]);
$sent=count(array_filter($recipients,fn($row)=>$row['status']==='sent'));$failed=count(array_filter($recipients,fn($row)=>$row['status']==='failed'));
$activePage='wishlist';$pageTitle='Interview outreach batch #'.$batchId.' · ResumeIQ';$pageStyles='<style>.batch-head{padding:24px;display:flex;align-items:center;justify-content:space-between;gap:18px}.batch-head h1{margin:7px 0 5px}.batch-meta{display:flex;gap:8px;flex-wrap:wrap}.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:10px}.metric{padding:18px}.metric small{display:block;color:var(--muted);margin-bottom:7px}.metric strong{font-size:22px}.recipient-panel{margin-top:10px;overflow:hidden}.recipient-head,.recipient-row{display:grid;grid-template-columns:minmax(220px,1.2fr) minmax(220px,1fr) 120px 170px;gap:12px;align-items:center;padding:13px 18px}.recipient-head{background:#fafafe;color:var(--muted);font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.05em}.recipient-row{border-top:1px solid var(--line)}.recipient-row strong,.recipient-row small{display:block}.recipient-row small{color:var(--muted);margin-top:3px}.state{display:inline-flex;width:max-content;padding:5px 8px;border-radius:7px;font-size:10px;font-weight:700}.state.sent{background:var(--green-soft);color:var(--green)}.state.failed{background:#fff1f3;color:var(--danger)}.state.pending{background:var(--amber-soft);color:var(--amber)}.error-copy{color:var(--danger)!important}@media(max-width:780px){.summary{grid-template-columns:1fr 1fr}.recipient-head{display:none}.recipient-row{grid-template-columns:1fr}.batch-head{align-items:flex-start;flex-direction:column}}</style>';require __DIR__.'/views/partials/header.php';
?>
<section class="panel batch-head"><div><div class="kicker"><i class="fa-solid fa-envelope-circle-check"></i> Interview outreach</div><h1>Batch #<?=(int)$batch['id']?> · <?=htmlspecialchars($batch['job_title']?:'Interview invitations')?></h1><div class="batch-meta"><span class="tag">Created <?=htmlspecialchars(date('d M Y, g:i A',strtotime($batch['created_at'])))?></span><span class="tag">Interview <?=htmlspecialchars($batch['interview_at']?date('d M Y, g:i A',strtotime($batch['interview_at'])):'Not scheduled')?></span><span class="tag"><?=htmlspecialchars($batch['timezone']?:'Timezone unavailable')?></span></div></div><a class="btn" href="interview_invite.php?job_id=<?=(int)$batch['job_id']?>"><i class="fa-solid fa-arrow-left"></i> Back to invitations</a></section>
<section class="summary"><article class="panel metric"><small>Total recipients</small><strong><?=count($recipients)?></strong></article><article class="panel metric"><small>Successfully sent</small><strong><?=$sent?></strong></article><article class="panel metric"><small>Failed</small><strong><?=$failed?></strong></article><article class="panel metric"><small>Batch status</small><strong><?=htmlspecialchars(ucfirst($batch['status']))?></strong></article></section>
<section class="panel recipient-panel"><div class="recipient-head"><span>Candidate</span><span>Email</span><span>Delivery</span><span>Sent at</span></div><?php foreach($recipients as $recipient):?><article class="recipient-row"><span><strong><?=htmlspecialchars($recipient['name']?:'Candidate record unavailable')?></strong><small><?=htmlspecialchars($recipient['role_title']?:'Role unavailable')?> · <?=htmlspecialchars($recipient['stage']?:'Stage unavailable')?></small></span><span><?=htmlspecialchars($recipient['email'])?></span><span><span class="state <?=htmlspecialchars($recipient['status'])?>"><?=htmlspecialchars(ucfirst($recipient['status']))?></span><?php if($recipient['error_text']):?><small class="error-copy"><?=htmlspecialchars($recipient['error_text'])?></small><?php endif?></span><span><?=htmlspecialchars($recipient['sent_at']?date('d M Y, g:i:s A',strtotime($recipient['sent_at'])):'Not sent')?></span></article><?php endforeach?><?php if(!$recipients):?><div class="empty">No recipients were stored for this batch.</div><?php endif?></section>
<link rel=stylesheet href=assets/interview-batch-actions.css><script>window.interviewBatchActionData=<?=json_encode(['csrf'=>csrfToken(),'batchId'=>$batchId,'recipients'=>array_map(fn($row)=>['candidate_id'=>$row['candidate_id'],'status'=>$row['status']],$recipients)],JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT)?>;</script><script src=assets/interview-batch-actions.js></script>
<?php require __DIR__.'/views/partials/footer.php';
