<?php
require_once __DIR__.'/lib/auth.php';requireAuth();require_once __DIR__.'/lib/workspace.php';
$pdo=db();$user=currentUser();$id=(int)($_GET['id']??$_POST['id']??0);$message='';
$stmt=$pdo->prepare('SELECT wp.*,j.title job_title,j.min_experience,j.preferred_skills_json FROM wishlist_profiles wp LEFT JOIN jobs j ON j.id=wp.job_id WHERE wp.id=? AND wp.user_id=?');$stmt->execute([$id,$user['id']]);$profile=$stmt->fetch();if(!$profile){http_response_code(404);exit('Job profile not found.');}
if($_SERVER['REQUEST_METHOD']==='POST'&&verifyCsrf($_POST['csrf']??'')){$skills=array_values(array_unique(array_filter(array_map('trim',preg_split('/[,\r\n]+/',$_POST['required_skills']??'')))));$pdo->prepare('UPDATE wishlist_profiles SET required_skills_json=? WHERE id=? AND user_id=?')->execute([json_encode($skills),$id,$user['id']]);$profile['required_skills_json']=json_encode($skills);$message='Required skills saved. Candidate scores now use only these skills.';}
$required=json_decode($profile['required_skills_json']??'[]',true)?:[];$candidates=array_values(array_filter(loadCandidateRecords(),fn($c)=>(int)($c['job_id']??0)===(int)($profile['job_id']??0)));$statusStmt=$pdo->prepare('SELECT candidate_id,disposition FROM wishlist_items WHERE profile_id=?');$statusStmt->execute([$id]);$statuses=[];foreach($statusStmt->fetchAll() as $row)$statuses[$row['candidate_id']]=$row['disposition'];foreach($candidates as &$candidate)$candidate['profile_match']=profileSkillMatch($candidate,$required);unset($candidate);usort($candidates,fn($a,$b)=>(int)$b['profile_match']['analyzed']<=>(int)$a['profile_match']['analyzed']?:(($b['profile_match']['score']??-1)<=>($a['profile_match']['score']??-1)));$selected=array_values(array_filter($candidates,fn($c)=>($statuses[$c['id']]??'')==='selected'));
$activePage='wishlist';$pageTitle=trim($profile['name']).' · ResumeIQ';$pageStyles='<style>.profile-grid{display:grid;grid-template-columns:350px 1fr;gap:10px}.box{padding:17px}.box textarea{min-height:130px}.rank{display:grid;grid-template-columns:34px 1fr 62px auto;gap:10px;align-items:center;padding:11px 0;border-bottom:1px solid var(--line)}.rank p{font-size:9px;color:var(--muted);margin:4px 0}.rank-num{font-weight:800;color:var(--primary)}.skill-list{display:flex;gap:5px;flex-wrap:wrap}.benefit{background:var(--green-soft);color:var(--green)}@media(max-width:800px){.profile-grid{grid-template-columns:1fr}}</style>';require __DIR__.'/views/partials/header.php';
?>
<section class="page-head"><div><div class="kicker"><i class="fa-solid fa-briefcase"></i> Job profile</div><h1><?=htmlspecialchars(trim($profile['name']))?></h1><p>Ranking uses Evidence v1 for applicants to this job: skills, relevant experience, preferred skills, role similarity and evidence strength.</p></div><a class="btn" href="wishlist.php?profile=<?=$id?>">Open wishlist</a></section><?php if($message):?><div class="panel" style="padding:10px;color:var(--green);margin-bottom:10px"><?=htmlspecialchars($message)?></div><?php endif?>
<section class="profile-grid"><aside class="panel box"><h2>Required skills</h2><p class="muted">Comma or new-line separated. Configured skills feed the Evidence v1 requirement mapping.</p><form method="post"><input type="hidden" name="csrf" value="<?=csrfToken()?>"><input type="hidden" name="id" value="<?=$id?>"><textarea class="control" name="required_skills" placeholder="PHP, Laravel, MySQL, REST API"><?=htmlspecialchars(implode(', ',$required))?></textarea><button class="btn btn-primary" style="margin-top:8px">Save & recalculate</button></form></aside><article class="panel box"><h2>Top 5 applicants</h2><?php if(!$required):?><div class="empty">Add required skills first. No Evidence v1 score is shown until required skills are configured.</div><?php endif?><?php foreach(array_slice($candidates,0,5) as $index=>$candidate):$d=candidatePresentation($candidate);$m=$candidate['profile_match'];?><div class="rank"><span class="rank-num">#<?=$index+1?></span><div><strong><a href="candidate_detail.php?id=<?=urlencode($candidate['id'])?>"><?=htmlspecialchars($d['name'])?></a></strong><p><?=count($m['matched'])?>/<?=count($required)?> required skills matched</p><div class="skill-list"><?php foreach(array_slice($m['matched'],0,5) as $skill):?><span class="tag"><?=htmlspecialchars($skill)?></span><?php endforeach?></div></div><b><?=$m['analyzed']?$m['score'].'%':($m['configured']?'Needs analysis':'?')?></b><span class="tag"><?=htmlspecialchars($statuses[$candidate['id']]??'not marked')?></span></div><?php endforeach?></article></section>
<section class="panel box" style="margin-top:10px"><h2>Selected candidates</h2><?php if(!$selected):?><div class="empty">No candidate selected for this job yet.</div><?php endif?><?php foreach($selected as $candidate):$d=candidatePresentation($candidate);?><div class="rank"><i class="fa-solid fa-check"></i><div><strong><a href="candidate_detail.php?id=<?=urlencode($candidate['id'])?>"><?=htmlspecialchars($d['name'])?></a></strong><p><?=htmlspecialchars($d['role'])?></p></div><b><?=$candidate['profile_match']['analyzed']?$candidate['profile_match']['score'].'%':($candidate['profile_match']['configured']?'Needs analysis':'?')?></b><span class="tag">Selected</span></div><?php endforeach?></section>
<?php require __DIR__.'/views/partials/footer.php';?>
