<?php
require_once __DIR__.'/lib/auth.php';
requireAuth();
require_once __DIR__.'/lib/workspace.php';
$jobId=(int)($_GET['job_id']??0);
$jobs=db()->query("SELECT id,title FROM jobs ORDER BY title")->fetchAll();
$items=loadCandidateRecords();
$jobName='All jobs';
if($jobId){$items=array_values(array_filter($items,fn($c)=>(int)($c['job_id']??0)===$jobId));$s=db()->prepare('SELECT title FROM jobs WHERE id=?');$s->execute([$jobId]);$jobName=$s->fetchColumn()?:'Job';}
$s=db()->prepare("SELECT DISTINCT er.candidate_id FROM email_recipients er JOIN email_batches eb ON eb.id=er.batch_id JOIN wishlist_profiles wp ON wp.id=eb.profile_id WHERE er.status='sent'".($jobId?' AND wp.job_id=?':''));
$s->execute($jobId?[$jobId]:[]);
$invited=array_fill_keys(array_map('strval',$s->fetchAll(PDO::FETCH_COLUMN)),true);
$stages=['Applied','Screening','Interview','Offer','Rejected'];
$activePage='pipeline';$pageTitle='Pipeline · ResumeIQ';
$pageStyles='<style>.pipeline-filter{display:grid;gap:5px;font-size:11px;color:var(--muted)}.pipeline-filter select{height:38px;min-width:230px;border:1px solid var(--line);border-radius:8px;background:#fff;padding:0 10px}.board{display:grid;grid-template-columns:repeat(5,minmax(230px,1fr));gap:9px;overflow-x:auto;margin-top:12px}.column{background:#f0f1f7;border:1px solid var(--line);border-radius:10px;padding:9px;min-height:520px}.column.over{outline:2px solid var(--primary)}.column-head{display:flex;justify-content:space-between;padding:5px 4px 11px;font-size:10px;font-weight:700}.card{display:block;background:#fff;border:1px solid var(--line);border-radius:8px;padding:11px;margin-bottom:7px;cursor:grab}.card strong{font-size:10px}.card p,.card-foot{font-size:8px;color:var(--muted)}.card-foot{display:flex;justify-content:space-between;border-top:1px dashed var(--line);padding-top:7px}.invite-mark{display:inline-flex;margin:7px 0;padding:4px 6px;border-radius:6px;background:#eafff6;color:#087a52;font-size:8px;font-weight:700}@media(max-width:850px){.board{grid-template-columns:repeat(5,250px)}}</style>';
require __DIR__.'/views/partials/header.php';
?>
<section class="page-head"><div><div class="kicker"><i class="fa-solid fa-table-columns"></i> Hiring workflow</div><h1><?=htmlspecialchars($jobName)?> pipeline</h1><p><?=count($items)?> applicants · drag cards between stages; every move saves.</p></div><label class="pipeline-filter">Job<select id="pipelineJob"><option value="0">All jobs</option><?php foreach($jobs as $job):?><option value="<?=(int)$job['id']?>" <?=$jobId===(int)$job['id']?'selected':''?>><?=htmlspecialchars($job['title'])?></option><?php endforeach?></select></label></section>
<section class="board"><?php foreach($stages as $stage):$group=array_values(array_filter($items,fn($x)=>($x['stage']??'Applied')===$stage));?><article class="column" data-stage="<?=$stage?>"><div class="column-head"><span><?=$stage?></span><b class="count"><?=count($group)?></b></div><div class="drop"><?php foreach($group as $c):$d=candidatePresentation($c);?><a class="card" draggable="true" data-id="<?=htmlspecialchars($c['id'])?>" href="candidate_detail.php?id=<?=urlencode($c['id'])?>"><strong><?=htmlspecialchars($d['name'])?></strong><p><?=htmlspecialchars($d['role'])?></p><?php if(isset($invited[(string)$c['id']])):?><span class="invite-mark"><i class="fa-solid fa-envelope-circle-check"></i> Interview invited</span><?php endif?><div class="card-foot"><span><?=htmlspecialchars($c['source']??'Unknown')?></span><span>Open profile</span></div></a><?php endforeach?></div></article><?php endforeach?></section>
<script>const token='<?=csrfToken()?>',cards=[...document.querySelectorAll('.card')],cols=[...document.querySelectorAll('.column')];let drag;document.getElementById('pipelineJob').onchange=e=>location.href=+e.target.value?'pipeline.php?job_id='+e.target.value:'pipeline.php';cards.forEach(c=>c.ondragstart=()=>drag=c);function counts(){cols.forEach(c=>c.querySelector('.count').textContent=c.querySelectorAll('.card').length)}cols.forEach(col=>{col.ondragover=e=>e.preventDefault();col.ondrop=async e=>{e.preventDefault();if(!drag)return;const old=drag.parentElement;col.querySelector('.drop').appendChild(drag);counts();const r=await fetch('pipeline_api.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({id:drag.dataset.id,stage:col.dataset.stage,csrf:token})});if(!r.ok){old.appendChild(drag);counts();alert('Move could not be saved')}}});</script>
<?php require __DIR__.'/views/partials/footer.php';?>
