<?php
require_once __DIR__.'/config/database.php';require_once __DIR__.'/lib/integrations.php';require_once __DIR__.'/lib/email_api_mailer.php';require_once __DIR__.'/lib/smtp_mailer.php';require_once __DIR__.'/lib/interview_confirmation.php';
header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');$origin=$_SERVER['HTTP_ORIGIN']??'';if($origin==='https://nonceblox.com'){header('Access-Control-Allow-Origin: https://nonceblox.com');header('Vary: Origin');}if($_SERVER['REQUEST_METHOD']==='OPTIONS'){header('Access-Control-Allow-Methods: GET, POST, OPTIONS');header('Access-Control-Allow-Headers: Content-Type');exit;}
function apiReply(array $payload,int $status=200): void{http_response_code($status);echo json_encode($payload,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
$input=$_SERVER['REQUEST_METHOD']==='POST'?(json_decode(file_get_contents('php://input'),true)?:$_POST):$_GET;$token=trim((string)($input['token']??''));if(!preg_match('/^[A-Za-z0-9_-]{40,60}$/',$token))apiReply(['ok'=>false,'error'=>'Invalid interview link.'],404);
$pdo=db();$stmt=$pdo->prepare("SELECT ii.*,ib.timezone,ib.status batch_status,c.name candidate_name,j.title job_title,s.starts_at confirmed_at FROM interview_invitations ii JOIN interview_batches ib ON ib.id=ii.batch_id JOIN candidates c ON c.id=ii.candidate_id JOIN jobs j ON j.id=ib.job_id LEFT JOIN interview_slots s ON s.id=ii.confirmed_slot_id WHERE ii.token_hash=? LIMIT 1");$stmt->execute([hash('sha256',$token)]);$invitation=$stmt->fetch();if(!$invitation)apiReply(['ok'=>false,'error'=>'Invalid interview link.'],404);
if($_SERVER['REQUEST_METHOD']==='GET'){
 if($invitation['status']==='confirmed')apiReply(['ok'=>true,'expired'=>true,'confirmed'=>true,'candidate'=>$invitation['candidate_name'],'job'=>$invitation['job_title'],'timezone'=>$invitation['timezone'],'confirmed_at'=>$invitation['confirmed_at']]);
 if($invitation['status']!=='awaiting_confirmation'||$invitation['batch_status']!=='active'||strtotime($invitation['expires_at'])<time())apiReply(['ok'=>true,'expired'=>true,'confirmed'=>false]);
 $slots=$pdo->prepare("SELECT id,starts_at,ends_at FROM interview_slots WHERE batch_id=? AND status='available' AND starts_at>=NOW() ORDER BY starts_at");$slots->execute([$invitation['batch_id']]);apiReply(['ok'=>true,'expired'=>false,'candidate'=>$invitation['candidate_name'],'job'=>$invitation['job_title'],'timezone'=>$invitation['timezone'],'slots'=>$slots->fetchAll()]);
}
if($_SERVER['REQUEST_METHOD']!=='POST')apiReply(['ok'=>false,'error'=>'Method not allowed.'],405);$slotId=(int)($input['slot_id']??0);if(!$slotId)apiReply(['ok'=>false,'error'=>'Choose an interview time.'],422);
try{$pdo->beginTransaction();$lock=$pdo->prepare("SELECT id,starts_at,ends_at FROM interview_slots WHERE id=? AND batch_id=? AND status='available' AND starts_at>=NOW() FOR UPDATE");$lock->execute([$slotId,$invitation['batch_id']]);$slot=$lock->fetch();$state=$pdo->prepare('SELECT status FROM interview_invitations WHERE id=? FOR UPDATE');$state->execute([$invitation['id']]);if($state->fetchColumn()!=='awaiting_confirmation')throw new RuntimeException('This link has already been used or expired.');if(!$slot)throw new RuntimeException('That time is no longer available.');$pdo->prepare("UPDATE interview_slots SET status='reserved',invitation_id=?,reserved_at=NOW() WHERE id=?")->execute([$invitation['id'],$slotId]);$pdo->prepare("UPDATE interview_invitations SET status='confirmed',confirmed_slot_id=? WHERE id=?")->execute([$slotId,$invitation['id']]);$pdo->prepare("INSERT INTO audit_events(user_id,action,entity_type,entity_id,metadata_json) VALUES(NULL,'interview.slot_confirmed','interview_invitation',?,?)")->execute([(string)$invitation['id'],json_encode(['candidate_id'=>$invitation['candidate_id'],'slot_id'=>$slotId,'starts_at'=>$slot['starts_at'],'outcome'=>'success'])]);$pdo->commit();$invitation['job_title']=$invitation['job_title'];$notification='sent';try{sendInterviewConfirmation($invitation,$slot);}catch(Throwable $mailError){$notification='failed';$pdo->prepare("INSERT INTO audit_events(user_id,action,entity_type,entity_id,metadata_json) VALUES(NULL,'interview.confirmation_email_failed','interview_invitation',?,?)")->execute([(string)$invitation['id'],json_encode(['outcome'=>'failed'])]);}apiReply(['ok'=>true,'confirmed'=>true,'expired'=>true,'confirmed_at'=>$slot['starts_at'],'timezone'=>$invitation['timezone'],'notification'=>$notification]);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();apiReply(['ok'=>false,'error'=>$e->getMessage()],409);}
