<?php
require_once __DIR__.'/lib/auth.php';requireAuth();require_once __DIR__.'/lib/integrations.php';
function normalizedJobTitle(string $title): string {$title=mb_strtolower(trim(preg_replace('/\s+/u',' ',$title)));return preg_replace('/^sr\.?\s+/u','senior ',$title);}
function noncebloxResumeUrl(?string $file): ?string {$file=trim((string)$file);if($file==='')return null;if(filter_var($file,FILTER_VALIDATE_URL))return in_array(parse_url($file,PHP_URL_SCHEME),['http','https'],true)?$file:null;$name=basename(str_replace('\\','/',$file));return $name===''?null:'https://nonceblox.com/uploads/'.rawurlencode($name);}
$config=integrationConfig('nonceblox_mysql');$error='';$message='';$jobs=[];$applicants=[];$local=db();
$lastSyncStmt=$local->prepare("SELECT created_at,metadata_json FROM audit_events WHERE action='source_sync_completed' AND entity_type='integration' AND entity_id='nonceblox_mysql' ORDER BY id DESC LIMIT 1");$lastSyncStmt->execute();$lastSync=$lastSyncStmt->fetch();$lastSyncMeta=$lastSync?json_decode($lastSync['metadata_json']??'{}',true):[];
try {
    if(($config['status']??'')!=='configured')throw new RuntimeException('Configure the NonceBlox database in Integrations first.');
    $remote=new PDO('mysql:host='.$config['host'].';port='.($config['port']?:3306).';dbname='.$config['database'].';charset=utf8mb4',$config['username'],integrationSecret($config,'password'),[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_TIMEOUT=>5]);
    $jobs=$remote->query('SELECT id,title,`desc`,tags,`date`,location,form_fields FROM career ORDER BY id DESC LIMIT 100')->fetchAll();
    $applicants=$remote->query('SELECT id,fname,lname,email,phone,remark,job_position,`date`,highest_qualification,ctc,city,state,exctc,file,equity,career_id,country FROM career_request ORDER BY id DESC LIMIT 2000')->fetchAll();
    if($_SERVER['REQUEST_METHOD']==='POST'&&verifyCsrf($_POST['csrf']??'')){
        if(($_POST['action']??'')!=='sync')throw new RuntimeException('Invalid sync action.');$local=db();$jobStmt=$local->prepare('INSERT INTO jobs(external_id,title,description,location) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE title=VALUES(title),description=VALUES(description),location=VALUES(location)');$existingJobs=$local->prepare('SELECT id FROM jobs WHERE external_id=? LIMIT 1');$jobMap=[];$titleMap=[];
        foreach($jobs as $job){$jobStmt->execute([(int)$job['id'],trim($job['title']),$job['desc'],$job['location']?:null]);$existingJobs->execute([(int)$job['id']]);$jobMap[(int)$job['id']]=(int)$existingJobs->fetchColumn();$titleMap[normalizedJobTitle($job['title'])]=$jobMap[(int)$job['id']];}
        $candidateStmt=$local->prepare('INSERT INTO candidates(id,job_id,name,role_title,email,phone,country_name,score,stage,source_name,skills_json,experience_json,analysis_json,source_url,stored_file,created_at) VALUES(?,?,?,?,?,?,?,0,\'Applied\',\'NonceBlox website\',\'[]\',\'{}\',\'{}\',?,?,?) ON DUPLICATE KEY UPDATE job_id=VALUES(job_id),name=VALUES(name),role_title=VALUES(role_title),email=VALUES(email),phone=VALUES(phone),country_name=VALUES(country_name),source_url=VALUES(source_url),stored_file=VALUES(stored_file)');
        foreach($applicants as $a){$id='WEB-'.substr(hash('sha256','nonceblox-career-'.$a['id']),0,20);$name=trim($a['fname'].' '.$a['lname'])?:'Website applicant';$created=date('Y-m-d H:i:s',strtotime($a['date']?:'now'));$resumeUrl=noncebloxResumeUrl($a['file']??null);$candidateStmt->execute([$id,$jobMap[(int)($a['career_id']??0)]??$titleMap[normalizedJobTitle($a['job_position']??'')]??null,$name,$a['job_position']?:'Candidate',$a['email']?:null,$a['phone']?:null,$a['country']?:null,$resumeUrl,$resumeUrl,$created]);}
        $syncedAt=date('Y-m-d H:i:s');$syncMeta=['jobs'=>count($jobs),'applicants'=>count($applicants)];$local->prepare('INSERT INTO audit_events(user_id,action,entity_type,entity_id,metadata_json) VALUES(?,?,?,?,?)')->execute([currentUser()['id']??null,'source_sync_completed','integration','nonceblox_mysql',json_encode($syncMeta)]);$lastSync=['created_at'=>$syncedAt];$lastSyncMeta=$syncMeta;
        $message=count($jobs).' jobs and '.count($applicants).' applicants synchronized.';
    }
} catch(Throwable $e){$error=$e instanceof RuntimeException?$e->getMessage():'Source connection failed. Check hostname, permissions and firewall.';}
$activePage='sources';$pageTitle='Source sync · ResumeIQ';$pageStyles='<style>.page-head>form{position:relative;z-index:2}.sync-action{display:flex;align-items:flex-end;flex-direction:column;gap:8px}.sync-action small{color:var(--muted);font-size:9px}.sync-progress{padding:16px;margin:12px 0}.sync-progress[hidden]{display:none}.sync-progress-head{display:flex;justify-content:space-between;gap:15px;margin-bottom:10px;font-size:10px}.progress-track{height:9px;border-radius:6px;background:var(--primary-soft);overflow:hidden}.progress-fill{width:0;height:100%;background:linear-gradient(90deg,var(--primary),#9d86ff);transition:width .25s ease}.btn:disabled{cursor:not-allowed;opacity:.65}.sync-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin:12px 0}.sync-stat{padding:15px}.sync-stat strong{display:block;font-size:21px}.sync-stat span{font-size:9px;color:var(--muted)}.sync-table{padding:15px;overflow:auto}.sync-table table{width:100%;border-collapse:collapse;font-size:9px}.sync-table th,.sync-table td{text-align:left;padding:9px;border-bottom:1px solid var(--line);white-space:nowrap}.sync-table a{color:var(--primary);font-weight:600}.notice{padding:10px;border-radius:8px;margin:10px 0;font-size:10px}.ok{background:var(--green-soft);color:var(--green)}.err{background:#fff1f3;color:var(--danger)}@media(max-width:650px){.sync-stats{grid-template-columns:1fr}}</style>';require __DIR__.'/views/partials/header.php';?>
<section class="page-head"><div><div class="kicker"><i class="fa-solid fa-rotate"></i> Website source</div><h1>NonceBlox career sync</h1><p>Read-only remote preview. Import into <?=htmlspecialchars($brand['name'])?> happens only when you press Sync now.</p></div><?php if(!$error):?><form method="post" id="syncForm" class="sync-action"><input type="hidden" name="csrf" value="<?=csrfToken()?>"><input type="hidden" name="action" value="sync"><button class="btn btn-primary" id="syncButton" type="submit"><i class="fa-solid fa-rotate"></i><span>Sync now</span></button><small><?php if($lastSync):?>Last synced <?=htmlspecialchars(date('d M Y, h:i A',strtotime($lastSync['created_at'])))?> · <?=(int)($lastSyncMeta['applicants']??0)?> applicants<?php else:?>Never synced<?php endif?></small></form><?php endif?></section><section class="panel sync-progress" id="syncProgress" hidden aria-live="polite"><div class="sync-progress-head"><strong id="syncProgressLabel">Preparing sync…</strong><span id="syncProgressPercent">0%</span></div><div class="progress-track" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-fill" id="syncProgressFill"></div></div></section><?php if($message):?><div class="notice ok"><?=htmlspecialchars($message)?></div><?php endif?><?php if($error):?><div class="notice err"><?=htmlspecialchars($error)?> <a href="integrations.php">Open integrations</a></div><?php endif?><section class="sync-stats"><article class="panel sync-stat"><strong><?=count($jobs)?></strong><span>Remote jobs</span></article><article class="panel sync-stat"><strong><?=count($applicants)?></strong><span>Remote applicants</span></article><article class="panel sync-stat"><strong><?=count(array_filter($applicants,fn($a)=>!empty($a['file'])))?></strong><span>Resume file references</span></article></section><section class="panel sync-table"><h2>Applicant preview</h2><table><thead><tr><th>Name</th><th>Job</th><th>Email</th><th>Location</th><th>Qualification</th><th>CTC</th><th>Resume</th></tr></thead><tbody><?php foreach($applicants as $a):$resumeUrl=noncebloxResumeUrl($a['file']??null);?><tr><td><?=htmlspecialchars(trim($a['fname'].' '.$a['lname']))?></td><td><?=htmlspecialchars($a['job_position'])?></td><td><?=htmlspecialchars($a['email'])?></td><td><?=htmlspecialchars(implode(', ',array_filter([$a['city'],$a['state'],$a['country']])))?></td><td><?=htmlspecialchars($a['highest_qualification'])?></td><td><?=htmlspecialchars($a['ctc'].' / '.$a['exctc'])?></td><td><?php if($resumeUrl):?><a href="<?=htmlspecialchars($resumeUrl)?>" target="_blank" rel="noopener noreferrer">Open resume <i class="fa-solid fa-arrow-up-right-from-square"></i></a><?php else:?>None<?php endif?></td></tr><?php endforeach?></tbody></table></section>
<?php if(!$error):?><script>(()=>{const form=document.getElementById('syncForm'),button=document.getElementById('syncButton'),buttonText=button.querySelector('span'),progress=document.getElementById('syncProgress'),fill=document.getElementById('syncProgressFill'),track=progress.querySelector('[role="progressbar"]'),label=document.getElementById('syncProgressLabel'),percent=document.getElementById('syncProgressPercent');form.addEventListener('submit',async event=>{event.preventDefault();button.disabled=true;buttonText.textContent='Syncing…';progress.hidden=false;const syncId=crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(16).slice(2);let offset=0;try{while(true){const body=new FormData(form);body.set('sync_id',syncId);body.set('offset',String(offset));const response=await fetch('source_sync_api.php',{method:'POST',body,credentials:'same-origin'});const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.message||'Sync failed.');offset=result.processed;fill.style.width=result.percent+'%';percent.textContent=result.percent+'%';track.setAttribute('aria-valuenow',String(result.percent));label.textContent=result.total?result.processed+' of '+result.total+' applicants synced':'No applicants to sync';if(result.complete){setTimeout(()=>location.reload(),350);break;}}}catch(error){label.textContent=error.message;label.style.color='var(--danger)';button.disabled=false;buttonText.textContent='Sync now';}});})();</script><?php endif?>
<?php require __DIR__.'/views/partials/footer.php';?>
