<?php
require_once __DIR__.'/interview_calendar_links.php';
function interviewConfirmationHtml(array $invitation,array $slot): string{
    $safe=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES|ENT_HTML5,'UTF-8');[$start,$end]=interviewCalendarDates($invitation,$slot);$when=$start->format('l, d F Y \a\t g:i A');$google=interviewGoogleCalendarUrl($invitation,$slot);$ics=interviewCalendarDownloadUrl((int)$invitation['id']);
    $structured=json_encode(['@context'=>'https://schema.org','@type'=>'EventReservation','reservationNumber'=>'NBX-INT-'.$invitation['id'],'reservationStatus'=>'https://schema.org/ReservationConfirmed','underName'=>['@type'=>'Person','name'=>$invitation['candidate_name']],'reservationFor'=>['@type'=>'Event','name'=>'Interview - '.$invitation['job_title'],'startDate'=>$start->format(DATE_ATOM),'endDate'=>$end->format(DATE_ATOM),'eventStatus'=>'https://schema.org/EventScheduled','location'=>['@type'=>'VirtualLocation','url'=>'https://resume.nonceblox.com/']]],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);
    return '<!doctype html><html><head><script type="application/ld+json">'.$structured.'</script></head><body style="margin:0;background:#f5f5f8;font-family:Arial,sans-serif;color:#191820"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="padding:32px 14px"><tr><td align="center"><table role="presentation" width="640" style="width:100%;max-width:640px;background:#fff;border:1px solid #e8e6ee;border-radius:12px"><tr><td style="padding:28px;border-bottom:1px solid #eceaf1"><strong style="font-size:22px;color:#6843e9">NonceBlox</strong></td></tr><tr><td style="padding:34px 28px"><div style="font-size:12px;color:#6843e9;font-weight:bold;text-transform:uppercase">Interview confirmed</div><h1 style="font-size:28px;margin:12px 0">'.$safe($invitation['job_title']).'</h1><p style="line-height:1.7;color:#625e6b">'.$safe($invitation['candidate_name']).' confirmed the interview schedule.</p><div style="padding:20px;background:#f7f5ff;border-radius:10px"><strong>'.$safe($when).'</strong><br><span style="color:#767080">'.$safe($invitation['timezone']).'</span></div><table role="presentation" cellpadding="0" cellspacing="0" style="margin-top:22px"><tr><td style="padding-right:10px"><a href="'.$safe($google).'" style="display:inline-block;padding:12px 17px;border-radius:7px;background:#6843e9;color:#fff;text-decoration:none;font-weight:bold">Add to Google Calendar</a></td><td><a href="'.$safe($ics).'" style="display:inline-block;padding:11px 16px;border:1px solid #d9d3eb;border-radius:7px;color:#443b59;text-decoration:none;font-weight:bold">Download .ics</a></td></tr></table><p style="margin-top:24px;color:#625e6b">This time is now locked. Contact the hiring team if a manual reschedule is required.</p></td></tr></table></td></tr></table></body></html>';
}
function sendInterviewConfirmation(array $invitation,array $slot): void{
    $settings=integrationConfig('interview_scheduling');$admins=$settings['admin_emails']??['chinka.gupta@nonceblox.com','hr@nonceblox.com'];$recipients=array_values(array_unique(array_filter(array_merge([$invitation['recipient_email']],$admins),fn($email)=>filter_var($email,FILTER_VALIDATE_EMAIL))));$subject='Interview confirmed - '.$invitation['job_title'];$html=interviewConfirmationHtml($invitation,$slot);$api=integrationConfig('email_api');if(($api['status']??'')!=='configured')$api=['status'=>'configured','url'=>'https://hrms-api.nonceblox.com/api/emails/send-multi-recipient'];if(!empty($api['url']))emailApiSendHtml($api,$recipients,$subject,$html);else{$smtp=integrationConfig('smtp');if(($smtp['status']??'')!=='configured')throw new RuntimeException('Confirmation email delivery is not configured.');foreach($recipients as $email)smtpSendHtml($smtp,$email,$subject,$html);}
}
