<?php
if($_SERVER['REQUEST_METHOD']==='POST'&&($_POST['action']??'')==='send'&&isset($_POST['availability_start'])){
 try{
  if(!verifyCsrf($_POST['csrf']??''))throw new RuntimeException('Invalid request.');if(!$deliveryReady)throw new RuntimeException('Configure email delivery before sending.');$window=validateInterviewWindow($_POST);$slots=buildInterviewSlots($window);$ids=array_values(array_unique(array_filter(array_map('strval',$_POST['candidate_ids']??[]))));$subject=trim((string)($_POST['subject']??''));$body=trim((string)($_POST['body']??''));if(!$ids||$subject===''||$body==='')throw new RuntimeException('Select recipients and complete the availability window.');
  $marks=implode(',',array_fill(0,count($ids),'?'));$recipientStmt=$pdo->prepare("SELECT c.id,c.name,c.email FROM candidates c WHERE c.job_id=? AND c.id IN ($marks) AND c.email IS NOT NULL AND c.email<>'' AND NOT EXISTS(SELECT 1 FROM interview_invite_locks il WHERE il.profile_id=? AND il.candidate_id=c.id AND il.active=1)");$recipientStmt->execute(array_merge([$jobId],$ids,[$profile['id']]));$recipients=$recipientStmt->fetchAll();if(count($recipients)!==count($ids))throw new RuntimeException('A selected candidate is invalid, missing email, or already invited.');
  sort($ids);$windowLabel=$window['start']->format('d M').' - '.$window['end']->format('d M Y');$interviewAt=$window['start']->format('Y-m-d').' '.$window['dailyStart'].':00';$dedupe=hash('sha256',$user['id'].'|'.$jobId.'|'.$subject.'|'.$windowLabel.'|'.$window['dailyStart'].'|'.$window['dailyEnd'].'|'.implode(',',$ids));$scheduleConfig=integrationConfig('interview_scheduling');$bookingBase=rtrim((string)($scheduleConfig['external_booking_url']??'https://nonceblox.com/interview-schedule.php'),'?&').'?' . 'token=';
  $pdo->beginTransaction();$pdo->prepare("INSERT INTO email_batches(user_id,profile_id,subject,body,interview_at,timezone,recipient_count,status,dedupe_key) VALUES(?,?,?,?,?,?,?,'sending',?)")->execute([$user['id'],$profile['id'],$subject,$body,$interviewAt,$window['timezone'],count($recipients),$dedupe]);$batchId=(int)$pdo->lastInsertId();$saved=persistInterviewScheduleForSend($pdo,$window,$slots,$recipients,$jobId,$profile,$batchId,$user,$job,$windowLabel,$bookingBase,$subject);$scheduleBatchId=$saved['batch_id'];$invitations=$saved['invitations'];$pdo->commit();
  $sent=0;$failed=0;$updateRecipient=$pdo->prepare('UPDATE email_recipients SET status=?,sent_at=?,error_text=? WHERE batch_id=? AND candidate_id=?');$move=$pdo->prepare("UPDATE candidates SET stage='Interview' WHERE id=? AND job_id=?");$lock=$pdo->prepare('INSERT INTO interview_invite_locks(profile_id,candidate_id,batch_id,active,locked_at,reset_at,reset_by) VALUES(?,?,?,1,NOW(),NULL,NULL) ON DUPLICATE KEY UPDATE batch_id=VALUES(batch_id),active=1,locked_at=NOW(),reset_at=NULL,reset_by=NULL');$audit=$pdo->prepare('INSERT INTO audit_events(user_id,action,entity_type,entity_id,metadata_json) VALUES(?,?,?,?,?)');
  foreach($recipients as $recipient){$invitation=$invitations[$recipient['id']];try{$deliverInterview($recipient['email'],$subject,$invitation['html']);$updateRecipient->execute(['sent',date('Y-m-d H:i:s'),null,$batchId,$recipient['id']]);$pdo->prepare("UPDATE interview_invitations SET status='awaiting_confirmation',sent_at=NOW() WHERE id=?")->execute([$invitation['id']]);$move->execute([$recipient['id'],$jobId]);$lock->execute([$profile['id'],$recipient['id'],$batchId]);$audit->execute([$user['id'],'interview.invitation_sent','candidate',$recipient['id'],json_encode(['batch_id'=>$batchId,'schedule_batch_id'=>$scheduleBatchId,'job_id'=>$jobId,'availability'=>$windowLabel,'timezone'=>$window['timezone'],'transport'=>$deliveryName,'booking_host'=>'nonceblox.com','outcome'=>'success'])]);$sent++;}catch(Throwable $mailError){$updateRecipient->execute(['failed',null,'Delivery failed.',$batchId,$recipient['id']]);$pdo->prepare("UPDATE interview_invitations SET status='failed' WHERE id=?")->execute([$invitation['id']]);$failed++;}}
  $status=$failed===0?'sent':($sent?'partial':'failed');$pdo->prepare('UPDATE email_batches SET status=? WHERE id=?')->execute([$status,$batchId]);$audit->execute([$user['id'],'interview.batch_completed','email_batch',(string)$batchId,json_encode(['schedule_batch_id'=>$scheduleBatchId,'job_id'=>$jobId,'sent'=>$sent,'failed'=>$failed,'outcome'=>$status])]);header('Location: interview_invite.php?job_id='.$jobId.'&scheduled='.$sent.'&failed='.$failed);exit;
 }catch(Throwable $schedulerError){if($pdo->inTransaction())$pdo->rollBack();$error=str_contains($schedulerError->getMessage(),'Duplicate entry')?'This exact invitation batch already exists.':$schedulerError->getMessage();$_POST['action']='scheduler_error';}
}
