USE resumeiq;
CREATE TABLE IF NOT EXISTS organization_settings (id TINYINT UNSIGNED PRIMARY KEY,name VARCHAR(160) NOT NULL DEFAULT 'ResumeIQ',logo_path VARCHAR(255) NULL,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB;
INSERT IGNORE INTO organization_settings(id,name) VALUES(1,'ResumeIQ');
ALTER TABLE candidates ADD COLUMN analysis_json JSON NULL AFTER experience_json;
